// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Koa Experts | TeamStation AI',
    description: 'Hire elite Koa experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireKoaPage() {
    return (
        <ProgrammaticContent
            technology="Koa"
            description="Our Koa experts are masters of the Node.js framework. We vet for a deep understanding of Koa's core principles, from its powerful middleware to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
