// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Figma Experts | TeamStation AI',
    description: 'Hire elite Figma experts, vetted for their expertise in building high-performance, scalable, and secure design systems. Build your team with TeamStation AI.',
};

export default function HireFigmaPage() {
    return (
        <ProgrammaticContent
            technology="Figma"
            description="Our Figma experts are masters of the design tool. We vet for a deep understanding of Figma's core principles, from its powerful design and prototyping features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable design systems."
            country={null}
        />
    );
}
