// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Istio Experts | TeamStation AI',
    description: 'Hire elite Istio experts, vetted for their expertise in building high-performance, scalable, and secure service meshes. Build your team with TeamStation AI.',
};

export default function HireIstioPage() {
    return (
        <ProgrammaticContent
            technology="Istio"
            description="Our Istio experts are masters of the service mesh. We vet for a deep understanding of Istio's core principles, from its powerful traffic management and observability features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable service meshes."
            country={null}
        />
    );
}
