// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire MongoDB Experts | TeamStation AI',
    description: 'Hire elite MongoDB experts, vetted for their expertise in building high-performance, scalable, and secure NoSQL databases. Build your team with TeamStation AI.',
};

export default function HireMongoDBPage() {
    return (
        <ProgrammaticContent
            technology="MongoDB"
            description="Our MongoDB experts are masters of the NoSQL database. We vet for a deep understanding of MongoDB's core principles, from its powerful data modeling and indexing features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable NoSQL databases."
            country={null}
        />
    );
}
