// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire LLM Experts | TeamStation AI',
    description: 'Hire elite LLM experts, vetted for their expertise in building high-performance, scalable, and secure AI-powered applications. Build your team with TeamStation AI.',
};

export default function HireLLMPage() {
    return (
        <ProgrammaticContent
            technology="LLM"
            description="Our LLM experts are masters of large language models. We vet for a deep understanding of LLM architecture, from the transformer model to the latest techniques in fine-tuning and prompt engineering. Our focus is on engineers who can build expert, cost-effective, and maintainable AI-powered applications."
            country={null}
        />
    );
}
