// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/Program-maticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire dbt Experts | TeamStation AI',
    description: 'Hire elite dbt experts, vetted for their expertise in building high-performance, scalable, and secure data transformation pipelines. Build your team with TeamStation AI.',
};

export default function HiredbtPage() {
    return (
        <ProgrammaticContent
            technology="dbt"
            description="Our dbt experts are masters of data transformation. We vet for a deep understanding of dbt's core principles, from writing clean and modular SQL to building complex, production-ready data transformation pipelines. Our focus is on engineers who can build expert, cost-effective, and maintainable data-native systems."
            country={null}
        />
    );
}
