
import {
    AlertTriangle,
    AppWindow,
    BadgeCheck,
    BarChart,
    BookOpen,
    BrainCircuit,
    Bug,
    CheckCircle,
    ChevronsRight,
    ClipboardList,
    Clock,
    Cloud,
    Code,
    CodeSquare,
    Codepen,
    Component,
    Compass,
    Contact,
    Cpu,
    Database,
    Dna,
    DollarSign,
    DraftingCompass,
    ExternalLink,
    FileLock,
    FileText,
    GanttChartSquare,
    GitBranch,
    GitCompare,
    Github,
    Gitlab,
    Globe,
    Handshake,
    HelpCircle,
    Key,
    KeyRound,
    Laptop,
    Layers,
    Link,
    Linkedin,
    Mail,
    Map,
    MessageCircle,
    MessageSquare,
    Package,
    PenTool,
    PersonStanding,
    Plane,
    Pyramid,
    RadioTower,
    Rocket,
    Scale,
    Search,
    Server,
    Settings,
    ShieldCheck,
    Siren,
    Slack,
    Sprout,
    Star,
    Target,
    TestTube2,
    TrendingUp,
    Trophy,
    UserCheck,
    UserCog,
    UserPlus,
    UserX,
    Users,
    Wallet,
    Webhook,
    Workflow,
    Youtube,
    Zap,
  } from "lucide-react";
import { TechEntry } from "./tech";
  
  export const allTech: Record<string, TechEntry> = {
    net: {
      name: ".NET",
      category: "Backend",
      categorySlug: "backend-developer",
      seo_title: "Hire Nearshore .NET Developers | TeamStation AI",
      meta_description:
        "Elite, pre-vetted .NET engineers in LATAM. Axiom Cortex™ vetting, EOR compliance, and audit-ready ops. Book a strategy call today.",
      intro:
        "Our developers are experts in building robust, scalable applications using the .NET framework.",
      pains: [
        {
          icon: Code,
          problem: "Monolithic architecture slowing down development",
          pain: "Your large, tightly-coupled .NET application is difficult to maintain and deploy, leading to slow development cycles and high regression risk.",
          solution:
            "We provide experts in microservices architecture who can break down your monolith into smaller, manageable services, improving agility and scalability.",
          kpi: "Reduced deployment time by 50% and decreased bug count by 30%.",
        },
        {
          icon: Cloud,
          problem: "High infrastructure costs",
          pain: "Your on-premise .NET infrastructure is expensive to maintain and doesn't scale efficiently with demand.",
          solution:
            "Our developers are proficient in migrating .NET applications to cloud platforms like Azure, optimizing for cost and performance.",
          kpi: "Lowered infrastructure costs by 40% and improved application performance by 25%.",
        },
        {
          icon: GitBranch,
          problem: "Lack of modern CI/CD practices",
          pain: "Your development process is manual and error-prone, resulting in slow releases and frequent rollbacks.",
          solution:
            "We implement modern CI/CD pipelines for .NET applications using tools like Azure DevOps, automating the build, test, and deployment process.",
          kpi: "Increased deployment frequency by 3x and reduced rollback rate by 90%.",
        },
      ],
      evaluation: [
        "Proficiency in C# and .NET Core",
        "Experience with Azure services",
        "Knowledge of microservices architecture",
        "Expertise in database design and optimization",
      ],
      technical_analysis:
        "Our .NET developers are vetted for their ability to design and build enterprise-grade applications. We focus on their understanding of software architecture, cloud-native development, and DevOps practices.",
      interlink_slugs: ["csharp", "azure", "sql-server"],
    },
    python: {
        name: "Python",
        category: "Backend",
        categorySlug: "backend-developer",
        seo_title: "Hire Nearshore Python Developers | TeamStation AI",
        meta_description:
          "AI-vetted Python engineers from LATAM. Build scalable, data-driven applications with top talent verified by Axiom Cortex™. Hire smarter, not harder.",
        intro:
          "Power your data-driven applications with our elite, AI-vetted Python developers from Latin America. We deliver senior engineers who specialize in building scalable, high-performance systems for data science, machine learning, and web applications.",
        pains: [
          {
            icon: BrainCircuit,
            pain: "Are you struggling to productionize your ML models?",
            problem:
              "Your data science team builds great models, but you lack the engineering expertise to deploy and scale them in a production environment. Your models are stuck in notebooks, not delivering business value.",
            solution:
              "We provide Python engineers who are experts in MLOps. They specialize in building robust, scalable pipelines for model training, deployment, and monitoring using tools like Docker, Kubernetes, and cloud-native services.",
            kpi: "Reduced time-to-market for new models by 70%.",
          },
          {
            icon: Database,
            pain: "Is your data pipeline slow and unreliable?",
            problem:
              "Your data processing is slow, error-prone, and can't handle growing data volumes. Your team spends more time firefighting than deriving insights from your data.",
            solution:
              "Our Python developers are proficient in building and optimizing large-scale data pipelines using frameworks like Spark and Airflow. They design resilient, scalable systems that deliver reliable data for your analytics and ML workloads.",
            kpi: "Increased data processing speed by 5x.",
          },
          {
            icon: Layers,
            pain: "Is your Django/Flask monolith a bottleneck?",
            problem:
              "Your monolithic web application is difficult to scale and maintain. Development is slow, and deploying new features is risky.",
            solution:
              "We provide Python architects who specialize in modernizing web applications. They can refactor your monolith into a scalable microservices architecture, improving agility and performance.",
            kpi: "Increased deployment frequency by 4x.",
          },
        ],
        evaluation: [
          "Deep expertise in Python and its data science ecosystem (Pandas, NumPy, Scikit-learn)",
          "Experience with web frameworks like Django and Flask",
          "Proficiency in building and scaling data pipelines (Spark, Airflow)",
          "Knowledge of MLOps best practices and tools (Docker, Kubernetes)",
          "Database design and optimization (SQL & NoSQL)",
          "Cloud-native development on AWS, GCP, or Azure",
        ],
        technical_analysis:
          "Our Axiom Cortex™ engine evaluates Python candidates for their ability to build and deploy production-grade data and web applications. We focus on their engineering fundamentals, problem-solving skills, and their ability to write clean, efficient, and maintainable code. We identify engineers who can bridge the gap between data science and software engineering.",
        interlink_slugs: ["django", "flask", "pandas", "docker", "kubernetes", "aws"],
      },
    go: {
        name: "Go",
        category: "Backend",
        categorySlug: "backend-developer",
        seo_title: "Hire Elite Go Developers & Engineers | TeamStation AI",
        meta_description: "Struggling to hire Go developers? Our AI-vetted, LATAM-based engineers build scalable, high-performance systems. Cut interview time by 80%.",
        intro: "Build high-performance, concurrent systems that scale effortlessly. Our elite Go developers from LATAM are rigorously vetted by our cognitive AI engine, ensuring they can solve your most complex engineering challenges from day one.",
        pains: [
          {
            icon: UserX,
            pain: "Is hiring Go experts a high-risk gamble?",
            problem: "The market is flooded with backend generalists, but finding true Go specialists who master concurrency and systems-level programming is a costly, time-consuming ordeal. A bad hire can cripple your project's performance.",
            solution: "We replace the resume lottery with verifiable proof. Our Axiom Cortex™ engine uses neuro-psychometric AI signals to identify elite talent with the right 'mental shape' for high-performance Go development, cutting your interview time by over 80%.",
            kpi: "Mismatch Rate ≤ 10%",
          },
          {
            icon: Rocket,
            pain: "Is your app hitting a performance wall?",
            problem: "Your platform struggles under heavy load. Slow response times, concurrency bottlenecks, and high latency are degrading the user experience and putting revenue at risk. Your current team lacks the specific expertise to re-architect for scale.",
            solution: "Our Go engineers specialize in building highly concurrent, low-latency microservices. They excel at performance optimization, leveraging goroutines and channels to build systems that handle massive traffic with maximum efficiency.",
            kpi: "Proven to handle 10x more concurrent users.",
          },
          {
            icon: GanttChartSquare,
            pain: "Are you drowning in DevOps and cloud complexity?",
            problem: "Your team is bogged down managing complex cloud infrastructure and CI/CD pipelines instead of shipping features. The operational overhead of deploying and scaling Go services is slowing your roadmap to a crawl.",
            solution: "We provide senior Go engineers with deep expertise in modern DevOps practices. They are masters of Docker, Kubernetes, and cloud-native ecosystems, enabling them to build, deploy, and manage resilient, scalable systems autonomously.",
            kpi: "Increased deployment frequency by 3x.",
          },
        ],
        evaluation: [
          "Mastery of Go's concurrency model (goroutines, channels)",
          "Systems design for scalable microservices architecture",
          "Expertise in gRPC, Protobuf, and API design",
          "Performance profiling and optimization techniques",
          "Cloud-native proficiency with Docker & Kubernetes",
          "Database optimization for high-throughput systems",
        ],
        technical_analysis: "Our Axiom Cortex™ evaluation for Go goes beyond simple coding tests. We use explainable psychometrics and cognitive calibration to assess a candidate's ability to reason about complex concurrent systems, solve performance bottlenecks, and design robust, scalable architectures. This bias mitigation software ensures we identify top-tier talent fairly and accurately.",
        interlink_slugs: ["docker", "kubernetes", "grpc", "technical-interview-evaluation", "build-vs-buy", "nearshore-vs-offshore"],
      },
      java: {
        name: "Java",
        category: "Backend",
        categorySlug: "backend-developer",
        seo_title: "Hire Nearshore Java Developers | TeamStation AI",
        meta_description:
          "AI-vetted Java engineers from LATAM. Build secure, scalable enterprise applications with top talent verified by Axiom Cortex™. Hire smarter, not harder.",
        intro:
          "Power your enterprise systems with our elite, AI-vetted Java developers from Latin America. We deliver senior engineers who specialize in building secure, scalable, and high-performance applications.",
        pains: [
          {
            icon: Layers,
            pain: "Is your legacy Java monolith a blocker?",
            problem:
              "Your aging monolithic Java application is difficult to update, scale, and maintain. Feature development is slow, and the risk of system-wide failure is high, stifling innovation and frustrating your team.",
            solution:
              "We provide Java architects who are experts in modernizing legacy systems. They specialize in safely decomposing monoliths into resilient, scalable microservices using frameworks like Spring Boot, improving agility and reducing technical debt.",
            kpi: "Reduced feature deployment time by 60%.",
          },
          {
            icon: ShieldCheck,
            pain: "Are you struggling to meet enterprise security and compliance?",
            problem:
              "Your team lacks the deep security expertise to build and maintain Java applications that meet strict enterprise and regulatory compliance standards (e.g., SOC 2, HIPAA). Security vulnerabilities are a constant threat.",
            solution:
              "Our Java engineers have extensive experience in building secure, compliant enterprise systems. They are proficient in security best practices, dependency management (e.g., Maven, Gradle), and implementing robust authentication and authorization.",
            kpi: "Zero critical vulnerabilities in the last 12 months.",
          },
          {
            icon: Cloud,
            pain: "Is your cloud strategy costly and inefficient?",
            problem:
              "Your Java applications are not optimized for the cloud. High operational costs, poor performance, and scalability issues are preventing you from realizing the full benefits of your cloud investment.",
            solution:
              "We provide cloud-native Java experts who can optimize your applications for performance and cost-efficiency on platforms like AWS and GCP. They are skilled in containerization with Docker, orchestration with Kubernetes, and leveraging cloud-managed services.",
            kpi: "Lowered cloud infrastructure costs by 35%.",
          },
        ],
        evaluation: [
          "Deep expertise in Java and the Spring Framework (Spring Boot, Spring Security)",
          "Microservices architecture and design patterns",
          "Cloud-native development (Docker, Kubernetes, AWS/GCP)",
          "Database design and optimization (SQL & NoSQL)",
          "CI/CD pipeline implementation and automation",
          "Application security and performance tuning",
        ],
        technical_analysis:
          "Our Axiom Cortex™ engine evaluates Java candidates for their ability to design and build complex, distributed systems. We focus on their understanding of software architecture, cloud-native principles, and their proficiency in writing clean, secure, and maintainable code. We identify engineers who can solve real-world enterprise challenges.",
        interlink_slugs: ["spring-boot", "kubernetes", "docker", "aws", "backend-developer", "technical-interview-evaluation"],
      },
      angular: {
        name: "Angular",
        category: "Frontend",
        categorySlug: "frontend-developer",
        seo_title: "Hire Nearshore Angular Developers | TeamStation AI",
        meta_description: "Build scalable web apps with elite Angular developers from LATAM. Our AI-vetted talent delivers clean code and robust solutions. Hire faster and smarter.",
        intro: "Develop enterprise-grade, scalable web applications with our top-tier Angular developers. We provide LATAM's finest, AI-vetted engineers who excel at building complex, high-performance frontends.",
        pains: [
            {
                icon: Component,
                pain: "Is your UI a complex, tangled mess?",
                problem: "Your Angular application has become a maze of tightly-coupled components, making it difficult to add new features or fix bugs without breaking something else. State management is inconsistent, and performance is degrading.",
                solution: "We provide Angular architects who are experts in building modular, maintainable applications. They implement robust state management with NgRx and design component libraries that promote reusability and simplify development.",
                kpi: "Reduced feature development time by 40%.",
            },
            {
                icon: TrendingUp,
                pain: "Are you failing to meet enterprise-level demands?",
                problem: "Your application struggles with scalability, security, and accessibility requirements. You lack the in-house expertise to implement the robust, enterprise-grade features that your customers are demanding.",
                solution: "Our senior Angular developers have a proven track record of building large-scale enterprise applications. They are experts in performance optimization, internationalization (i18n), and implementing strict security protocols.",
                kpi: "Achieved a 95+ score in Lighthouse performance audits.",
            },
            {
                icon: Bug,
                pain: "Is your legacy AngularJS app holding you back?",
                problem: "You're stuck with an outdated AngularJS application that is no longer supported, poses security risks, and prevents you from using modern web development practices. The migration path to a modern Angular version seems overwhelming.",
                solution: "We provide specialists in AngularJS to modern Angular migrations. Our developers create a strategic, phased migration plan that minimizes disruption, improves performance, and brings your application up to modern standards.",
                kpi: "Successfully migrated 5+ legacy enterprise applications.",
            },
        ],
        evaluation: [
            "Deep knowledge of Angular framework and TypeScript",
            "Proficiency in state management with NgRx or similar",
            "Experience with RxJS for reactive programming",
            "Expertise in building and testing complex SPAs",
            "Component library design and architecture",
            "Performance optimization and lazy loading techniques",
        ],
        technical_analysis: "Our cognitive AI engine vets Angular candidates for their architectural thinking and problem-solving skills. We assess their ability to design scalable component architectures, manage complex state, and write clean, performant, and testable code. We ensure they are not just coders, but true front-end engineers.",
        interlink_slugs: ["typescript", "rxjs", "ngrx", "frontend-developer", "technical-interview-evaluation"],
    },
    vue: {
      name: "Vue.js",
      category: "Frontend",
      categorySlug: "frontend-developer",
      seo_title: "Hire Nearshore Vue.js Developers | TeamStation AI",
      meta_description: "Hire top Vue.js developers from LATAM, vetted by our cognitive AI. Build performant, maintainable, and elegant user interfaces with elite talent.",
      intro: "Build beautiful, high-performance user interfaces with our elite, AI-vetted Vue.js developers from Latin America. We provide senior engineers who specialize in creating elegant, maintainable, and scalable front-end applications.",
      pains: [
          {
              icon: Layers,
              pain: "Is your front-end codebase a monolith?",
              problem: "Your UI is a single, tightly-coupled application, making it difficult to innovate and slow to deploy. You want to adopt micro-frontends, but your team lacks the expertise to implement them correctly with Vue.js.",
              solution: "We provide Vue.js experts who are proficient in architecting and building micro-frontend solutions. They can help you break down your monolith into independent, scalable components, improving development velocity and team autonomy.",
              kpi: "Increased deployment frequency by 3x.",
          },
          {
              icon: Rocket,
              pain: "Is your application's performance lagging?",
              problem: "Your Vue.js app suffers from slow load times, poor rendering performance, and a sluggish user experience. Your team struggles to identify and fix the performance bottlenecks that are frustrating your users.",
              solution: "Our senior Vue.js developers are masters of front-end performance optimization. They excel at code splitting, lazy loading, and leveraging Vue's reactivity system to build blazing-fast applications that delight users.",
              kpi: "Improved Lighthouse performance score by 30 points.",
          },
          {
              icon: GanttChartSquare,
              pain: "Are you struggling to scale your Vue app?",
              problem: "As your application grows, managing state becomes increasingly complex and error-prone. Your team is spending more time debugging state-related issues than building new features.",
              solution: "We provide Vue.js engineers with deep expertise in state management patterns and libraries like Pinia and Vuex. They design scalable, maintainable state architectures that can handle the complexity of large-scale applications.",
              kpi: "Reduced state-related bugs by 50%.",
          },
      ],
      evaluation: [
          "Mastery of Vue.js (Vue 2 & Vue 3) and its ecosystem",
          "Expertise in state management with Pinia or Vuex",
          "Proficiency with Nuxt.js for server-side rendering",
          "Component library design and best practices",
          "Front-end performance optimization techniques",
          "Test-driven development with Vitest or Jest",
      ],
      technical_analysis: "Our Axiom Cortex™ engine evaluates Vue.js candidates for their ability to build high-quality, scalable front-end applications. We assess their understanding of reactive programming, component architecture, and their proficiency in writing clean, performant, and testable code. We identify engineers who can create exceptional user experiences.",
      interlink_slugs: ["vuex", "nuxtjs", "pinia", "frontend-developer", "technical-interview-evaluation"],
  },
  nextjs: {
    name: "Next.js",
    category: "Full Stack",
    categorySlug: "full-stack-developer",
    seo_title: "Hire Nearshore Next.js Developers | TeamStation AI",
    meta_description: "Build scalable, high-performance web applications with elite Next.js developers from LATAM. Our AI-vetted talent delivers server-side rendering, static site generation, and seamless developer experiences.",
    intro: "Develop modern, scalable, and high-performance web applications with our top-tier Next.js developers. We provide LATAM's finest, AI-vetted engineers who excel at leveraging the full power of the React ecosystem to build exceptional user experiences.",
    pains: [
        {
            icon: Server,
            pain: "Are you struggling with slow, client-side rendered apps?",
            problem: "Your React SPA has poor SEO performance and a slow initial page load, which hurts user engagement and conversion rates. You need the benefits of server-side rendering, but your team lacks the expertise.",
            solution: "We provide Next.js experts who can build or migrate your application to leverage server-side rendering (SSR) and static site generation (SSG). This improves SEO, enhances performance, and delivers a superior user experience.",
            kpi: "Improved First Contentful Paint (FCP) by 60%.",
        },
        {
            icon: Globe,
            pain: "Is managing a separate backend and frontend slowing you down?",
            problem: "The complexity of coordinating a separate front-end and back-end team is creating communication overhead and slowing down your development lifecycle. You need to move faster and simplify your architecture.",
            solution: "Our full-stack Next.js developers are proficient in building end-to-end solutions. They can handle everything from database design and API development to front-end implementation, enabling you to build and ship features faster with a unified team.",
            kpi: "Reduced time-to-market for new features by 40%.",
        },
        {
            icon: ShieldCheck,
            pain: "Are you concerned about the security and scalability of your app?",
            problem: "You need to build an application that is not only fast but also secure and scalable. You're worried about implementing authentication, managing serverless functions, and ensuring your infrastructure can handle traffic spikes.",
            solution: "We provide senior Next.js engineers with deep expertise in building secure, scalable applications. They are proficient in implementing robust authentication, leveraging serverless functions for scalability, and deploying on modern hosting platforms like Vercel.",
            kpi: "Zero security incidents and 99.99% uptime.",
        },
    ],
    evaluation: [
        "Deep expertise in React and the Next.js framework",
        "SSR, SSG, and Incremental Static Regeneration (ISR)",
        "API route development and serverless functions",
        "Full-stack development experience",
        "Performance optimization and image handling",
        "Deployment and hosting on platforms like Vercel",
    ],
    technical_analysis: "Our cognitive AI engine vets Next.js candidates for their ability to architect and build modern, full-stack web applications. We assess their understanding of both front-end and back-end development, their proficiency in React, and their ability to leverage Next.js features to create performant, scalable, and secure applications.",
    interlink_slugs: ["react", "vercel", "full-stack-developer", "technical-interview-evaluation"],
},
  langchain: {
    name: "LangChain",
    category: "AI/ML",
    categorySlug: "ai-ml-engineer",
    seo_title: "Hire Nearshore LangChain Developers | TeamStation AI",
    meta_description: "Build powerful, AI-driven applications with elite LangChain developers from LATAM. Our AI-vetted talent specializes in LLM integration, prompt engineering, and building intelligent agents.",
    intro: "Harness the power of large language models (LLMs) with our top-tier LangChain developers. We provide LATAM's finest, AI-vetted engineers who excel at building sophisticated, AI-driven applications that can reason, act, and solve complex problems.",
    pains: [
        {
            icon: BrainCircuit,
            pain: "Are you struggling to build reliable, production-ready LLM apps?",
            problem: "You're excited about the potential of LLMs, but building robust, production-grade applications is harder than it looks. You're facing challenges with prompt engineering, managing context, and ensuring consistent, reliable outputs.",
            solution: "We provide LangChain experts who specialize in building dependable, scalable AI applications. They are masters of prompt engineering, managing conversational memory, and chaining LLM calls to create sophisticated agents that deliver predictable results.",
            kpi: "Improved output accuracy by 80%.",
        },
        {
            icon: Link,
            pain: "Is your LLM just a chatbot? Are you failing to connect it to real-world data?",
            problem: "Your LLM application is stuck in a sandbox, unable to interact with your proprietary data sources and APIs. You're missing the opportunity to build truly valuable, context-aware AI solutions that can automate complex workflows.",
            solution: "Our LangChain developers are proficient in integrating LLMs with external data sources and APIs. They can build custom tools and agents that allow your AI to access real-time information, interact with your existing systems, and take meaningful actions.",
            kpi: "Automated 50% of a complex business process.",
        },
        {
            icon: Scale,
            pain: "Are you worried about the cost and scalability of your LLM solution?",
            problem: "You're concerned that your LLM application will be too expensive to operate and won't scale to meet user demand. You need an architecture that is both cost-effective and highly scalable.",
            solution: "We provide senior LangChain engineers with expertise in building scalable, cost-optimized AI architectures. They can help you choose the right models, implement caching strategies, and leverage serverless infrastructure to build solutions that are both powerful and efficient.",
            kpi: "Reduced operational costs by 40%.",
        },
    ],
    evaluation: [
        "Deep expertise in Python and the LangChain framework",
        "Prompt engineering and optimization techniques",
        "Building and managing conversational agents",
        "Integrating LLMs with external data and APIs",
        "Knowledge of different LLM providers and models",
        "Deploying and scaling AI applications",
    ],
    technical_analysis: "Our cognitive AI engine vets LangChain candidates for their ability to architect and build sophisticated AI-driven applications. We assess their understanding of LLMs, their proficiency in prompt engineering, and their ability to build robust, scalable, and cost-effective solutions. We identify engineers who can turn your AI vision into a reality.",
    interlink_slugs: ["python", "openai", "llm", "ai-ml-engineer", "technical-interview-evaluation"],
},
typescript: {
    name: "TypeScript",
    category: "Full Stack",
    categorySlug: "full-stack-developer",
    seo_title: "Hire Nearshore TypeScript Developers | TeamStation AI",
    meta_description: "Build robust, scalable, and maintainable applications with elite TypeScript developers from LATAM. Our AI-vetted talent delivers clean code, strong type safety, and fewer bugs.",
    intro: "Elevate your codebase with our top-tier TypeScript developers. We provide LATAM's finest, AI-vetted engineers who excel at building large-scale, maintainable, and error-free applications for both the front-end and back-end.",
    pains: [
        {
            icon: Bug,
            pain: "Are runtime errors and 'undefined' is not a function killing your productivity?",
            problem: "Your JavaScript codebase is riddled with bugs that are only discovered at runtime. Your team is spending more time fixing preventable errors than shipping new features, and the lack of type safety makes refactoring a nightmare.",
            solution: "We provide TypeScript experts who can introduce strong type safety into your project. They can help you migrate your existing JavaScript codebase to TypeScript, catching errors at compile time and making your code more robust, predictable, and easier to refactor.",
            kpi: "Reduced runtime errors by 70%.",
        },
        {
            icon: Users,
            pain: "Is it difficult to onboard new developers and scale your team?",
            problem: "Your large, untyped JavaScript codebase is difficult for new developers to understand. The lack of clear contracts and self-documenting code slows down onboarding and makes it challenging to scale your team effectively.",
            solution: "Our TypeScript developers are masters of creating clean, self-documenting code. By leveraging TypeScript's features like interfaces and types, they make your codebase easier to navigate and understand, enabling new team members to become productive faster.",
            kpi: "Reduced onboarding time for new developers by 50%.",
        },
        {
            icon: Code,
            pain: "Are you struggling to maintain and refactor your large-scale application?",
            problem: "As your application grows, your JavaScript codebase becomes increasingly complex and difficult to maintain. Refactoring is a high-risk activity that often introduces new bugs, and you lack the confidence to make large-scale changes.",
            solution: "We provide senior TypeScript engineers who are experts in building and maintaining large-scale applications. They use TypeScript to create a more robust and maintainable architecture, enabling you to refactor with confidence and scale your application without fear.",
            kpi: "Increased developer confidence in refactoring by 90%.",
        },
    ],
    evaluation: [
        "Deep expertise in TypeScript and its advanced features",
        "Experience with both front-end (React, Angular, Vue) and back-end (Node.js) development",
        "Migrating large JavaScript codebases to TypeScript",
        "Best practices for type safety and code organization",
        "Test-driven development in a TypeScript environment",
        "Performance optimization and build configuration",
    ],
    technical_analysis: "Our cognitive AI engine vets TypeScript candidates for their ability to write clean, maintainable, and robust code. We assess their understanding of type theory, their ability to apply TypeScript effectively in both front-end and back-end contexts, and their proficiency in architecting large-scale, scalable applications. We identify engineers who can help you build a better, more reliable codebase.",
    interlink_slugs: ["javascript", "react", "nodejs", "full-stack-developer", "technical-interview-evaluation"],
}
  };
  