
import type { ElementType } from 'react';
import {
  Server,
  Layers,
  Plane,
  Database,
  Component,
  BrainCircuit,
  GanttChartSquare,
  ShieldCheck,
  TestTube2,
  Wallet,
  Briefcase, // for IT & Enterprise
  LineChart, // for Product & Growth
  Cpu, // for Operating Systems
  Code, // for Legacy Languages
  Network, // for Architecture & Integrations
} from 'lucide-react';

export interface TechCategory {
  name: string;
  slug: string;
  pain: string;
  icon: ElementType;
  tech: Array<{ name: string; slug: string }>;
}

export const techCategories: TechCategory[] = [
  {
    name: 'APIs & Backend Services',
    slug: 'backend-services',
    pain: "Is your backend a bottleneck or a force multiplier?",
    icon: Server,
    tech: [
      { name: 'Node.js', slug: 'node' },
      { name: 'Python', slug: 'python' },
      { name: 'Java', slug: 'java' },
      { name: 'Go', slug: 'golang' },
      { name: '.NET', slug: 'net' },
      { name: 'Ruby on Rails', slug: 'ruby' },
      { name: 'PHP', slug: 'php' },
      { name: 'gRPC', slug: 'grpc' },
      { name: 'GraphQL', slug: 'graphql' },
      { name: 'CodeIgniter', slug: 'codeigniter' },
      { name: 'Django', slug: 'django' },
      { name: 'Express', slug: 'express' },
      { name: 'FastAPI', slug: 'fastapi' },
      { name: 'Flask', slug: 'flask' },
      { name: 'Hapi.js', slug: 'hapi-js' },
      { name: 'Jakarta EE', slug: 'jakarta-ee' },
      { name: 'Koa', slug: 'koa' },
      { name: 'Micronaut', slug: 'micronaut' },
      { name: 'Rust', slug: 'rust' },
      { name: 'Dart', slug: 'dart' },
      { name: 'C++', slug: 'cpp' },
    ],
  },
    {
    name: 'Architecture & Integrations',
    slug: 'architecture-integrations',
    pain: "Is your architecture holding you back?",
    icon: Network,
    tech: [
      { name: 'API Gateway', slug: 'api-gateway' },
      { name: 'API Security', slug: 'api-security' },
      { name: 'Domain Driven Design', slug: 'domain-driven-design' },
      { name: 'Event Sourcing', slug: 'event-sourcing' },
      { name: 'Message Queues', slug: 'message-queues' },
      { name: 'Microservices', slug: 'microservices' },
    ],
  },
    {
    name: 'Vetting & Cognitive AI',
    slug: 'vetting-cognitive-ai',
    pain: "Are you hiring the right people?",
    icon: BrainCircuit,
    tech: [
      { name: 'Axiom Cortex', slug: 'axiom-cortex' },
    ],
    },
      {
    name: 'DevOps & Cloud Infrastructure',
    slug: 'devops-cloud',
    pain: "Is your infrastructure holding your business back?",
    icon: Server,
    tech: [
      { name: 'CI/CD', slug: 'ci-cd' },
      { name: 'Cloudformation', slug: 'cloudformation' },
      { name: 'Docker', slug: 'docker' },
      { name: 'GitOps', slug: 'gitops' },
      { name: 'Google Cloud', slug: 'google-cloud' },
      { name: 'Helm', slug: 'helm' },
      { name: 'Jenkins', slug: 'jenkins' },
    ],
    },
  {
    name: 'Frontend & UI/UX',
    slug: 'frontend-web',
    pain: "Is a slow, buggy UI costing you customers?",
    icon: Layers,
    tech: [
      { name: 'React/TypeScript', slug: 'react' },
      { name: 'Next.js', slug: 'nextjs' },
      { name: 'Vite', slug: 'vite' },
      { name: 'Angular', slug: 'angular' },
      { name: 'Vue.js', slug: 'vue' },
      { name: 'TanStack Query', slug: 'tanstack' },
      { name: 'Redux/Zustand', slug: 'redux' },
      { name: 'Tailwind/shadcn', slug: 'tailwind' },
      { name: 'Testing Library', slug: 'testing' },
      { name: 'Astro', slug: 'astro' },
      { name: 'Ember.js', slug: 'ember-js' },
      { name: 'Flow', slug: 'flow' },
      { name: 'Gatsby', slug: 'gatsby' },
      { name: 'jQuery', slug: 'jquery' },
      { name: 'MobX', slug: 'mobx' },
      { name: 'Nuxt.js', slug: 'nuxt-js' },
      { name: 'Svelte', slug: 'svelte' },
      { name: 'Solid.js', slug: 'solid-js' },
      { name: 'Preact', slug: 'preact' },
    ],
  },
  {
    name: 'Mobile & Cross-Platform',
    slug: 'mobile-cross-platform',
    pain: "Is your mobile experience falling behind?",
    icon: Plane,
    tech: [
      { name: 'React Native', slug: 'react-native' },
      { name: 'Flutter', slug: 'flutter' },
      { name: 'Swift', slug: 'swift' },
      { name: 'Kotlin', slug: 'kotlin' },
      { name: 'Socket.IO', slug: 'socketio' },
      { name: 'Android', slug: 'android' },
      { name: 'Dart', slug: 'dart' },
    ],
  },
    {
    name: 'Data & AI',
    slug: 'data-ai',
    pain: "Is your data a liability or your most valuable asset?",
    icon: Database,
    tech: [
      { name: 'Data Engineering', slug: 'data-engineering' },
      { name: 'dbt', slug: 'dbt' },
      { name: 'Snowflake', slug: 'snowflake' },
      { name: 'Apache Spark', slug: 'apache-spark' },
      { name: 'Machine Learning', slug: 'machine-learning' },
      { name: 'Data Science', slug: 'data-science' },
      { name: 'Pandas', slug: 'pandas' },
      { name: 'NumPy', slug: 'numpy' },
    ],
  },
  {
    name: 'Data Modeling & Databases',
    slug: 'data-modeling-databases',
    pain: "Is your data model built for scale or for future refactors?",
    icon: Database,
    tech: [
      { name: 'PostgreSQL', slug: 'postgresql' },
      { name: 'MySQL', slug: 'mysql' },
      { name: 'SQL Server', slug: 'sql' },
      { name: 'Prisma', slug: 'prisma' },
      { name: 'SQLAlchemy', slug: 'sqlalchemy' },
      { name: 'Hibernate', slug: 'hibernate' },
      { name: 'Redis', slug: 'redis' },
      { name: 'Memcached', slug: 'memcached' },
      { name: 'DynamoDB', slug: 'dynamodb' },
      { name: 'DataHub', slug: 'datahub' },
      { name: 'Great Expectations', slug: 'great-expectations' },
      { name: 'Cassandra', slug: 'cassandra' },
      { name: 'Elasticsearch', slug: 'elasticsearch' },
      { name: 'MongoDB', slug: 'mongodb' },
    ],
  },
  {
    name: 'Pipelines & Orchestration',
    slug: 'pipelines-orchestration',
    pain: "Are your data pipelines brittle and unreliable?",
    icon: Component,
    tech: [
      { name: 'Airflow', slug: 'airflow' },
      { name: 'Kafka', slug: 'kafka' },
      { name: 'Flink/Beam', slug: 'flink' },
      { name: 'Kubernetes', slug: 'kubernetes' },
      { name: 'Docker', slug: 'docker' },
    ],
  },
  {
    name: 'ML/AI & LLM Ops',
    slug: 'ml-ai-llm-ops',
    pain: "Struggling to move AI from a notebook to production?",
    icon: BrainCircuit,
    tech: [
      { name: 'LLMs', slug: 'llms' },
      { name: 'PyTorch', slug: 'pytorch' },
      { name: 'Transformers', slug: 'transformers' },
      { name: 'vLLM', slug: 'vllm' },
      { name: 'Ray Serve', slug: 'ray' },
      { name: 'LangChain', slug: 'langchain' },
      { name: 'pgvector', slug: 'pgvector' },
      { name: 'MLflow', slug: 'mlflow' },
      { name: 'Ragas', slug: 'ragas' },
      { name: 'OpenAI', slug: 'openai' },
      { name: 'DVC', slug: 'dvc' },
      { name: 'Feast', slug: 'feast' },
      { name: 'Kubeflow', slug: 'kubeflow' },
      { name: 'Hugging Face', slug: 'hugging-face' },
    ],
  },
  {
    name: 'Observability & SRE',
    slug: 'platform-infra-sre',
    pain: "Are you debugging in the dark when systems fail?",
    icon: GanttChartSquare,
    tech: [
      { name: 'Prometheus', slug: 'prometheus' },
      { name: 'Grafana', slug: 'grafana' },
      { name: 'OpenTelemetry', slug: 'opentelemetry' },
      { name: 'Jaeger/Loki', slug: 'jaeger' },
      { name: 'Terraform/Pulumi', slug: 'terraform' },
      { name: 'Istio/Linkerd', slug: 'istio' },
      { name: 'Ansible', slug: 'ansible' },
    ],
  },
    {
    name: 'Operating Systems',
    slug: 'operating-systems',
    pain: "Is your OS holding your business back?",
    icon: Cpu,
    tech: [
      { name: 'AIX', slug: 'aix' },
    ],
  },
  {
    name: 'Security & GRC',
    slug: 'security-grc',
    pain: "Is compliance an afterthought or built into your stack?",
    icon: ShieldCheck,
    tech: [
      { name: 'Vault', slug: 'vault' },
      { name: 'Okta/Auth0', slug: 'okta' },
      { name: 'CodeQL/Snyk', slug: 'codeql' },
      { name: 'Trivy', slug: 'trivy' },
      { name: 'OPA', slug: 'opa' },
      { name: 'SOC 2', slug: 'soc' },
      { name: 'ISO 27001', slug: 'iso' },
      { name: 'HIPAA', slug: 'hipaa' },
    ],
  },
    {
    name: 'Legacy Languages',
    slug: 'legacy-languages',
    pain: "Are your legacy systems holding you back?",
    icon: Code,
    tech: [
      { name: 'Algol', slug: 'algol' },
    ],
  },
  {
    name: 'Testing & Quality Engineering',
    slug: 'qa-quality-engineering',
    pain: "Does 'shipping fast' also mean 'shipping bugs'?",
    icon: TestTube2,
    tech: [
      { name: 'Playwright/Cypress', slug: 'playwright' },
      { name: 'Jest/Vitest', slug: 'jest' },
      { name: 'PyTest/JUnit', slug: 'pytest' },
      { name: 'k6/Locust', slug: 'k6' },
      { name: 'Pact', slug: 'pact' },
      { name: 'Gremlin', slug: 'gremlin' },
      { name: 'OWASP ZAP', slug: 'owasp-zap' },
    ],
  },
  {
    name: 'Cloud FinOps & BizTech',
    slug: 'finops-biztech',
    pain: "Are runaway cloud costs eating into your margins?",
    icon: Wallet,
    tech: [
      { name: 'CloudZero', slug: 'cloudzero' },
      { name: 'Infracost', slug: 'infracost' },
      { name: 'AWS Cost Explorer', slug: 'aws-cost-explorer' },
      { name: 'Salesforce', slug: 'salesforce' },
      { name: 'HubSpot', slug: 'hubspot' },
      { name: 'Hightouch/Census', slug: 'hightouch' },
    ],
  },
   {
    name: 'Product & Growth',
    slug: 'product-design-growth',
    pain: "Are you building features that users actually want?",
    icon: LineChart,
    tech: [
      { name: 'Amplitude', slug: 'amplitude' },
      { name: 'LaunchDarkly', slug: 'launchdarkly' },
      { name: 'Figma', slug: 'figma' },
    ],
  },
  {
    name: 'IT & Enterprise',
    slug: 'it-enterprise-ops',
    pain: "Is your IT infrastructure holding your business back?",
    icon: Briefcase,
    tech: [
      { name: 'Google Workspace', slug: 'google-workspace' },
      { name: 'Jamf', slug: 'jamf' },
      { name: 'Jira Service Mgmt', slug: 'jira-service-management' },
    ],
  },
];
