
import {
    AlertTriangle,
    AppWindow,
    BadgeCheck,
    BarChart,
    BookOpen,
    BrainCircuit,
    Bug,
    CheckCircle,
    ChevronsRight,
    ClipboardList,
    Clock,
    Cloud,
    Code,
    CodeSquare,
    Codepen,
    Component,
    Compass,
    Contact,
    Cpu,
    Database,
    Dna,
    DollarSign,
    DraftingCompass,
    ExternalLink,
    FileLock,
    FileText,
    GanttChartSquare,
    GitBranch,
    GitCompare,
    Github,
    Gitlab,
    Globe,
    Handshake,
    HelpCircle,
    Key,
    KeyRound,
    Laptop,
    Layers,
    Link,
    Linkedin,
    Mail,
    Map,
    MessageCircle,
    MessageSquare,
    Package,
    PenTool,
    PersonStanding,
    Plane,
    Pyramid,
    RadioTower,
    Rocket,
    Scale,
    Search,
    Server,
    Settings,
    ShieldCheck,
    Siren,
    Slack,
    Sprout,
    Star,
    Target,
    TestTube2,
    TrendingUp,
    Trophy,
    UserCheck,
    UserCog,
    UserPlus,
    UserX,
    Users,
    Wallet,
    Webhook,
    Workflow,
    Youtube,
    Zap,
  } from "lucide-react";
import { TechEntry } from "./tech";
  
  export const allTech: Record<string, TechEntry> = {
    net: {
      name: ".NET",
      category: "Backend",
      categorySlug: "backend-developer",
      seo_title: "Hire Nearshore .NET Developers | TeamStation AI",
      meta_description:
        "Elite, pre-vetted .NET engineers in LATAM. Axiom Cortex™ vetting, EOR compliance, and audit-ready ops. Book a strategy call today.",
      intro:
        "Our developers are experts in building robust, scalable applications using the .NET framework.",
      pains: [
        {
          icon: Code,
          problem: "Monolithic architecture slowing down development",
          pain: "Your large, tightly-coupled .NET application is difficult to maintain and deploy, leading to slow development cycles and high regression risk.",
          solution:
            "We provide experts in microservices architecture who can break down your monolith into smaller, manageable services, improving agility and scalability.",
          kpi: "Reduced deployment time by 50% and decreased bug count by 30%.",
        },
        {
          icon: Cloud,
          problem: "High infrastructure costs",
          pain: "Your on-premise .NET infrastructure is expensive to maintain and doesn't scale efficiently with demand.",
          solution:
            "Our developers are proficient in migrating .NET applications to cloud platforms like Azure, optimizing for cost and performance.",
          kpi: "Lowered infrastructure costs by 40% and improved application performance by 25%.",
        },
        {
          icon: GitBranch,
          problem: "Lack of modern CI/CD practices",
          pain: "Your development process is manual and error-prone, resulting in slow releases and frequent rollbacks.",
          solution:
            "We implement modern CI/CD pipelines for .NET applications using tools like Azure DevOps, automating the build, test, and deployment process.",
          kpi: "Increased deployment frequency by 3x and reduced rollback rate by 90%.",
        },
      ],
      evaluation: [
        "Proficiency in C# and .NET Core",
        "Experience with Azure services",
        "Knowledge of microservices architecture",
        "Expertise in database design and optimization",
      ],
      technical_analysis:
        "Our .NET developers are vetted for their ability to design and build enterprise-grade applications. We focus on their understanding of software architecture, cloud-native development, and DevOps practices.",
      interlink_slugs: ["csharp", "azure", "sql-server"],
    },
    go: {
        name: "Go",
        category: "Backend",
        categorySlug: "backend-developer",
        seo_title: "Hire Elite Go Developers & Engineers | TeamStation AI",
        meta_description: "Struggling to hire Go developers? Our AI-vetted, LATAM-based engineers build scalable, high-performance systems. Cut interview time by 80%.",
        intro: "Build high-performance, concurrent systems that scale effortlessly. Our elite Go developers from LATAM are rigorously vetted by our cognitive AI engine, ensuring they can solve your most complex engineering challenges from day one.",
        pains: [
          {
            icon: UserX,
            pain: "Is hiring Go experts a high-risk gamble?",
            problem: "The market is flooded with backend generalists, but finding true Go specialists who master concurrency and systems-level programming is a costly, time-consuming ordeal. A bad hire can cripple your project's performance.",
            solution: "We replace the resume lottery with verifiable proof. Our Axiom Cortex™ engine uses neuro-psychometric AI signals to identify elite talent with the right 'mental shape' for high-performance Go development, cutting your interview time by over 80%.",
            kpi: "Mismatch Rate ≤ 10%",
          },
          {
            icon: Rocket,
            pain: "Is your app hitting a performance wall?",
            problem: "Your platform struggles under heavy load. Slow response times, concurrency bottlenecks, and high latency are degrading the user experience and putting revenue at risk. Your current team lacks the specific expertise to re-architect for scale.",
            solution: "Our Go engineers specialize in building highly concurrent, low-latency microservices. They excel at performance optimization, leveraging goroutines and channels to build systems that handle massive traffic with maximum efficiency.",
            kpi: "Proven to handle 10x more concurrent users.",
          },
          {
            icon: GanttChartSquare,
            pain: "Are you drowning in DevOps and cloud complexity?",
            problem: "Your team is bogged down managing complex cloud infrastructure and CI/CD pipelines instead of shipping features. The operational overhead of deploying and scaling Go services is slowing your roadmap to a crawl.",
            solution: "We provide senior Go engineers with deep expertise in modern DevOps practices. They are masters of Docker, Kubernetes, and cloud-native ecosystems, enabling them to build, deploy, and manage resilient, scalable systems autonomously.",
            kpi: "Increased deployment frequency by 3x.",
          },
        ],
        evaluation: [
          "Mastery of Go's concurrency model (goroutines, channels)",
          "Systems design for scalable microservices architecture",
          "Expertise in gRPC, Protobuf, and API design",
          "Performance profiling and optimization techniques",
          "Cloud-native proficiency with Docker & Kubernetes",
          "Database optimization for high-throughput systems",
        ],
        technical_analysis: "Our Axiom Cortex™ evaluation for Go goes beyond simple coding tests. We use explainable psychometrics and cognitive calibration to assess a candidate's ability to reason about complex concurrent systems, solve performance bottlenecks, and design robust, scalable architectures. This bias mitigation software ensures we identify top-tier talent fairly and accurately.",
        interlink_slugs: ["docker", "kubernetes", "grpc", "technical-interview-evaluation", "build-vs-buy", "nearshore-vs-offshore"],
      },
      java: {
        name: "Java",
        category: "Backend",
        categorySlug: "backend-developer",
        seo_title: "Hire Nearshore Java Developers | TeamStation AI",
        meta_description:
          "AI-vetted Java engineers from LATAM. Build secure, scalable enterprise applications with top talent verified by Axiom Cortex™. Hire smarter, not harder.",
        intro:
          "Power your enterprise systems with our elite, AI-vetted Java developers from Latin America. We deliver senior engineers who specialize in building secure, scalable, and high-performance applications.",
        pains: [
          {
            icon: Layers,
            pain: "Is your legacy Java monolith a blocker?",
            problem:
              "Your aging monolithic Java application is difficult to update, scale, and maintain. Feature development is slow, and the risk of system-wide failure is high, stifling innovation and frustrating your team.",
            solution:
              "We provide Java architects who are experts in modernizing legacy systems. They specialize in safely decomposing monoliths into resilient, scalable microservices using frameworks like Spring Boot, improving agility and reducing technical debt.",
            kpi: "Reduced feature deployment time by 60%.",
          },
          {
            icon: ShieldCheck,
            pain: "Are you struggling to meet enterprise security and compliance?",
            problem:
              "Your team lacks the deep security expertise to build and maintain Java applications that meet strict enterprise and regulatory compliance standards (e.g., SOC 2, HIPAA). Security vulnerabilities are a constant threat.",
            solution:
              "Our Java engineers have extensive experience in building secure, compliant enterprise systems. They are proficient in security best practices, dependency management (e.g., Maven, Gradle), and implementing robust authentication and authorization.",
            kpi: "Zero critical vulnerabilities in the last 12 months.",
          },
          {
            icon: Cloud,
            pain: "Is your cloud strategy costly and inefficient?",
            problem:
              "Your Java applications are not optimized for the cloud. High operational costs, poor performance, and scalability issues are preventing you from realizing the full benefits of your cloud investment.",
            solution:
              "We provide cloud-native Java experts who can optimize your applications for performance and cost-efficiency on platforms like AWS and GCP. They are skilled in containerization with Docker, orchestration with Kubernetes, and leveraging cloud-managed services.",
            kpi: "Lowered cloud infrastructure costs by 35%.",
          },
        ],
        evaluation: [
          "Deep expertise in Java and the Spring Framework (Spring Boot, Spring Security)",
          "Microservices architecture and design patterns",
          "Cloud-native development (Docker, Kubernetes, AWS/GCP)",
          "Database design and optimization (SQL & NoSQL)",
          "CI/CD pipeline implementation and automation",
          "Application security and performance tuning",
        ],
        technical_analysis:
          "Our Axiom Cortex™ engine evaluates Java candidates for their ability to design and build complex, distributed systems. We focus on their understanding of software architecture, cloud-native principles, and their proficiency in writing clean, secure, and maintainable code. We identify engineers who can solve real-world enterprise challenges.",
        interlink_slugs: ["spring-boot", "kubernetes", "docker", "aws", "backend-developer", "technical-interview-evaluation"],
      },
      angular: {
        name: "Angular",
        category: "Frontend",
        categorySlug: "frontend-developer",
        seo_title: "Hire Nearshore Angular Developers | TeamStation AI",
        meta_description: "Build scalable web apps with elite Angular developers from LATAM. Our AI-vetted talent delivers clean code and robust solutions. Hire faster and smarter.",
        intro: "Develop enterprise-grade, scalable web applications with our top-tier Angular developers. We provide LATAM's finest, AI-vetted engineers who excel at building complex, high-performance frontends.",
        pains: [
            {
                icon: Component,
                pain: "Is your UI a complex, tangled mess?",
                problem: "Your Angular application has become a maze of tightly-coupled components, making it difficult to add new features or fix bugs without breaking something else. State management is inconsistent, and performance is degrading.",
                solution: "We provide Angular architects who are experts in building modular, maintainable applications. They implement robust state management with NgRx and design component libraries that promote reusability and simplify development.",
                kpi: "Reduced feature development time by 40%.",
            },
            {
                icon: TrendingUp,
                pain: "Are you failing to meet enterprise-level demands?",
                problem: "Your application struggles with scalability, security, and accessibility requirements. You lack the in-house expertise to implement the robust, enterprise-grade features that your customers are demanding.",
                solution: "Our senior Angular developers have a proven track record of building large-scale enterprise applications. They are experts in performance optimization, internationalization (i18n), and implementing strict security protocols.",
                kpi: "Achieved a 95+ score in Lighthouse performance audits.",
            },
            {
                icon: Bug,
                pain: "Is your legacy AngularJS app holding you back?",
                problem: "You're stuck with an outdated AngularJS application that is no longer supported, poses security risks, and prevents you from using modern web development practices. The migration path to a modern Angular version seems overwhelming.",
                solution: "We provide specialists in AngularJS to modern Angular migrations. Our developers create a strategic, phased migration plan that minimizes disruption, improves performance, and brings your application up to modern standards.",
                kpi: "Successfully migrated 5+ legacy enterprise applications.",
            },
        ],
        evaluation: [
            "Deep knowledge of Angular framework and TypeScript",
            "Proficiency in state management with NgRx or similar",
            "Experience with RxJS for reactive programming",
            "Expertise in building and testing complex SPAs",
            "Component library design and architecture",
            "Performance optimization and lazy loading techniques",
        ],
        technical_analysis: "Our cognitive AI engine vets Angular candidates for their architectural thinking and problem-solving skills. We assess their ability to design scalable component architectures, manage complex state, and write clean, performant, and testable code. We ensure they are not just coders, but true front-end engineers.",
        interlink_slugs: ["typescript", "rxjs", "ngrx", "frontend-developer", "technical-interview-evaluation"],
    },
  };