// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Flutter Experts | TeamStation AI',
    description: 'Hire elite Flutter experts, vetted for their expertise in building high-performance, scalable, and secure mobile applications. Build your team with TeamStation AI.',
};

export default function HireFlutterPage() {
    return (
        <ProgrammaticContent
            technology="Flutter"
            description="Our Flutter experts are masters of the cross-platform framework. We vet for a deep understanding of Flutter's core principles, from its powerful widget system to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable mobile applications."
            country={null}
        />
    );
}
