
import puppeteer from 'puppeteer';

const urls = [
  "https://cto.teamstation.dev/",
  "https://cto.teamstation.dev/about",
  "https://cto.teamstation.dev/case-studies",
  "https://cto.teamstation.dev/case-studies/atticus",
  "https://cto.teamstation.dev/case-studies/global-entertainment-platform",
  "https://cto.teamstation.dev/case-studies/global-ooh-advertising-platform",
  "https://cto.teamstation.dev/case-studies/healthcare-revenue-platform",
  "https://cto.teamstation.dev/case-studies/parsable",
  "https://cto.teamstation.dev/case-studies/rmj-technologies",
  "https://cto.teamstation.dev/comparisons",
  "https://cto.teamstation.dev/comparisons/andela",
  "https://cto.teamstation.dev/comparisons/bairesdev",
  "https://cto.teamstation.dev/comparisons/coderslink",
  "https://cto.teamstation.dev/comparisons/deel",
  "https://cto.teamstation.dev/comparisons/devlane",
  "https://cto.teamstation.dev/comparisons/globant",
  "https://cto.teamstation.dev/comparisons/howdy",
  "https://cto.teamstation.dev/comparisons/kms",
  "https://cto.teamstation.dev/comparisons/nearsure",
  "https://cto.teamstation.dev/comparisons/new-gen-nearshore",
  "https://cto.teamstation.dev/comparisons/parallelstaff",
  "https://cto.teamstation.dev/comparisons/revelo",
  "https://cto.teamstation.dev/comparisons/tecla",
  "https://cto.teamstation.dev/comparisons/terminal",
  "https://cto.teamstation.dev/comparisons/toptal",
  "https://cto.teamstation.dev/comparisons/unosquare",
  "https://cto.teamstation.dev/faq",
  "https://cto.teamstation.dev/hire",
  "https://cto.teamstation.dev/hire/by-country",
  "https://cto.teamstation.dev/hire/by-country/argentina",
  "https://cto.teamstation.dev/hire/by-country/argentina/angular",
  "https://cto.teamstation.dev/hire/by-country/argentina/go",
  "https://cto.teamstation.dev/hire/by-country/argentina/java",
  "https://cto.teamstation.dev/hire/by-country/argentina/net",
  "https://cto.teamstation.dev/hire/by-country/argentina/nextjs",
  "https://cto.teamstation.dev/hire/by-country/argentina/node",
  "https://cto.teamstation.dev/hire/by-country/argentina/python",
  "https://cto.teamstation.dev/hire/by-country/argentina/react",
  "https://cto.teamstation.dev/hire/by-country/argentina/vue",
  "https://cto.teamstation.dev/hire/by-country/brazil",
  "https://cto.teamstation.dev/hire/by-country/brazil/angular",
  "https://cto.teamstation.dev/hire/by-country/brazil/go",
  "https://cto.teamstation.dev/hire/by-country/brazil/java",
  "https://cto.teamstation.dev/hire/by-country/brazil/net",
  "https://cto.teamstation.dev/hire/by-country/brazil/nextjs",
  "https://cto.teamstation.dev/hire/by-country/brazil/node",
  "https://cto.teamstation.dev/hire/by-country/brazil/python",
  "https://cto.teamstation.dev/hire/by-country/brazil/react",
  "https://cto.teamstation.dev/hire/by-country/brazil/vue",
  "https://cto.teamstation.dev/hire/by-country/chile",
  "https://cto.teamstation.dev/hire/by-country/chile/angular",
  "https://cto.teamstation.dev/hire/by-country/chile/go",
  "https://cto.teamstation.dev/hire/by-country/chile/java",
  "https://cto.teamstation.dev/hire/by-country/chile/net",
  "https://cto.teamstation.dev/hire/by-country/chile/nextjs",
  "https://cto.teamstation.dev/hire/by-country/chile/node",
  "https://cto.teamstation.dev/hire/by-country/chile/python",
  "https://cto.teamstation.dev/hire/by-country/chile/react",
  "https://cto.teamstation.dev/hire/by-country/chile/vue",
  "https://cto.teamstation.dev/hire/by-country/colombia",
  "https://cto.teamstation.dev/hire/by-country/colombia/angular",
  "https://cto.teamstation.dev/hire/by-country/colombia/go",
  "https://cto.teamstation.dev/hire/by-country/colombia/java",
  "https://cto.teamstation.dev/hire/by-country/colombia/net",
  "https://cto.teamstation.dev/hire/by-country/colombia/nextjs",
  "https://cto.teamstation.dev/hire/by-country/colombia/node",
  "https://cto.teamstation.dev/hire/by-country/colombia/python",
  "https://cto.teamstation.dev/hire/by-country/colombia/react",
  "https://cto.teamstation.dev/hire/by-country/colombia/vue",
  "https://cto.teamstation.dev/hire/by-country/costa-rica",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/angular",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/go",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/java",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/net",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/nextjs",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/node",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/python",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/react",
  "https://cto.teamstation.dev/hire/by-country/costa-rica/vue",
  "https://cto.teamstation.dev/hire/by-country/ecuador",
  "https://cto.teamstation.dev/hire/by-country/ecuador/angular",
  "https://cto.teamstation.dev/hire/by-country/ecuador/go",
  "https://cto.teamstation.dev/hire/by-country/ecuador/java",
  "https://cto.teamstation.dev/hire/by-country/ecuador/net",
  "https://cto.teamstation.dev/hire/by-country/ecuador/nextjs",
  "https://cto.teamstation.dev/hire/by-country/ecuador/node",
  "https://cto.teamstation.dev/hire/by-country/ecuador/python",
  "https://cto.teamstation.dev/hire/by-country/ecuador/react",
  "https://cto.teamstation.dev/hire/by-country/ecuador/vue",
  "https://cto.teamstation.dev/hire/by-country/guatemala",
  "https://cto.teamstation.dev/hire/by-country/guatemala/angular",
  "https://cto.teamstation.dev/hire/by-country/guatemala/go",
  "https://cto.teamstation.dev/hire/by-country/guatemala/java",
  "https://cto.teamstation.dev/hire/by-country/guatemala/net",
  "https://cto.teamstation.dev/hire/by-country/guatemala/nextjs",
  "https://cto.teamstation.dev/hire/by-country/guatemala/node",
  "https://cto.teamstation.dev/hire/by-country/guatemala/python",
  "https://cto.teamstation.dev/hire/by-country/guatemala/react",
  "https://cto.teamstation.dev/hire/by-country/guatemala/vue",
  "https://cto.teamstation.dev/hire/by-country/mexico",
  "https://cto.teamstation.dev/hire/by-country/mexico/angular",
  "https://cto.teamstation.dev/hire/by-country/mexico/go",
  "https://cto.teamstation.dev/hire/by-country/mexico/java",
  "https://cto.teamstation.dev/hire/by-country/mexico/net",
  "https://cto.teamstation.dev/hire/by-country/mexico/nextjs",
  "https://cto.teamstation.dev/hire/by-country/mexico/node",
  "https://cto.teamstation.dev/hire/by-country/mexico/python",
  "https://cto.teamstation.dev/hire/by-country/mexico/react",
  "https://cto.teamstation.dev/hire/by-country/mexico/vue",
  "https://cto.teamstation.dev/hire/by-country/peru",
  "https://cto.teamstation.dev/hire/by-country/peru/angular",
  "https://cto.teamstation.dev/hire/by-country/peru/go",
  "https://cto.teamstation.dev/hire/by-country/peru/java",
  "https://cto.teamstation.dev/hire/by-country/peru/net",
  "https://cto.teamstation.dev/hire/by-country/peru/nextjs",
  "https://cto.teamstation.dev/hire/by-country/peru/node",
  "https://cto.teamstation.dev/hire/by-country/peru/python",
  "https://cto.teamstation.dev/hire/by-country/peru/react",
  "https://cto.teamstation.dev/hire/by-country/peru/vue",
  "https://cto.teamstation.dev/hire/by-country/uruguay",
  "https://cto.teamstation.dev/hire/by-country/uruguay/angular",
  "https://cto.teamstation.dev/hire/by-country/uruguay/go",
  "https://cto.teamstation.dev/hire/by-country/uruguay/java",
  "https://cto.teamstation.dev/hire/by-country/uruguay/net",
  "https://cto.teamstation.dev/hire/by-country/uruguay/nextjs",
  "https://cto.teamstation.dev/hire/by-country/uruguay/node",
  "https://cto.teamstation.dev/hire/by-country/uruguay/python",
  "https://cto.teamstation.dev/hire/by-country/uruguay/react",
  "https://cto.teamstation.dev/hire/by-country/uruguay/vue",
  "https://cto.teamstation.dev/hire/by-role",
  "https://cto.teamstation.dev/hire/by-role/backend-services",
  "https://cto.teamstation.dev/hire/by-role/data-engineering-analytics",
  "https://cto.teamstation.dev/hire/by-role/finops-biztech",
  "https://cto.teamstation.dev/hire/by-role/frontend-web",
  "https://cto.teamstation.dev/hire/by-role/it-enterprise-ops",
  "https://cto.teamstation.dev/hire/by-role/ml-ai-llm-ops",
  "https://cto.teamstation.dev/hire/by-role/mobile-cross-platform",
  "https://cto.teamstation.dev/hire/by-role/platform-infra-sre",
  "https://cto.teamstation.dev/hire/by-role/product-design-growth",
  "https://cto.teamstation.dev/hire/by-role/qa-quality-engineering",
  "https://cto.teamstation.dev/hire/by-role/security-grc",
  "https://cto.teamstation.dev/hire/by-team-topologies",
  "https://cto.teamstation.dev/hire/by-technology",
  "https://cto.teamstation.dev/hire/by-technology/airflow",
  "https://cto.teamstation.dev/hire/by-technology/amplitude",
  "https://cto.teamstation.dev/hire/by-technology/angular",
  "https://cto.teamstation.dev/hire/by-technology/appcenter",
  "https://cto.teamstation.dev/hire/by-technology/aws",
  "https://cto.teamstation.dev/hire/by-technology/aws-cost-explorer",
  "https://cto.teamstation.dev/hire/by-technology/browserstack",
  "https://cto.teamstation.dev/hire/by-technology/cloudzero",
  "https://cto.teamstation.dev/hire/by-technology/codeql",
  "https://cto.teamstation.dev/hire/by-technology/codepush",
  "https://cto.teamstation.dev/hire/by-technology/crowdstrike",
  "https://cto.teamstation.dev/hire/by-technology/dbt",
  "https://cto.teamstation.dev/hire/by-technology/detox",
  "https://cto.teamstation.dev/hire/by-technology/docker",
  "https://cto.teamstation.dev/hire/by-technology/dvc",
  "https://cto.teamstation.dev/hire/by-technology/dynamodb",
  "https://cto.teamstation.dev/hire/by-technology/edr",
  "https://cto.teamstation.dev/hire/by-technology/ef-core",
  "https://cto.teamstation.dev/hire/by-technology/external-secrets",
  "https://cto.teamstation.dev/hire/by-technology/fastlane",
  "https://cto.teamstation.dev/hire/by-technology/feast",
  "https://cto.teamstation.dev/hire/by-technology/figma",
  "https://cto.teamstation.dev/hire/by-technology/fivetran",
  "https://cto.teamstation.dev/hire/by-technology/flink",
  "https://cto.teamstation.dev/hire/by-technology/flutter",
  "https://cto.teamstation.dev/hire/by-technology/github-actions",
  "https://cto.teamstation.dev/hire/by-technology/go",
  "https://cto.teamstation.dev/hire/by-technology/google-workspace",
  "https://cto.teamstation.dev/hire/by-technology/grafana",
  "https://cto.teamstation.dev/hire/by-technology/graphql",
  "https://cto.teamstation.dev/hire/by-technology/great-expectations",
  "https://cto.teamstation.dev/hire/by-technology/gremlin",
  "https://cto.teamstation.dev/hire/by-technology/grpc",
  "https://cto.teamstation.dev/hire/by-technology/hibernate",
  "https://cto.teamstation.dev/hire/by-technology/hightouch",
  "https://cto.teamstation.dev/hire/by-technology/hipaa",
  "https://cto.teamstation.dev/hire/by-technology/hubspot",
  "https://cto.teamstation.dev/hire/by-technology/istio",
  "https://cto.teamstation.dev/hire/by-technology/iso",
  "https://cto.teamstation.dev/hire/by-technology/jaeger",
  "https://cto.teamstation.dev/hire/by-technology/jamf",
  "https://cto.teamstation.dev/hire/by-technology/java",
  "https://cto.teamstation.dev/hire/by-technology/jest",
  "https://cto.teamstation.dev/hire/by-technology/jira",
  "https://cto.teamstation.dev/hire/by-technology/jira-service-management",
  "https://cto.teamstation.dev/hire/by-technology/k6",
  "https://cto.teamstation.dev/hire/by-technology/kafka",
  "https://cto.teamstation.dev/hire/by-technology/kotlin",
  "https://cto.teamstation.dev/hire/by-technology/kubeflow",
  "https://cto.teamstation.dev/hire/by-technology/kubernetes",
  "https://cto.teamstation.dev/hire/by-technology/langchain",
  "https://cto.teamstation.dev/hire/by-technology/launchdarkly",
  "https://cto.teamstation.dev/hire/by-technology/looker",
  "https://cto.teamstation.dev/hire/by-technology/memcached",
  "https://cto.teamstation.dev/hire/by-technology/mlflow",
  "https://cto.teamstation.dev/hire/by-technology/mysql",
  "https://cto.teamstation.dev/hire/by-technology/net",
  "https://cto.teamstation.dev/hire/by-technology/nextjs",
  "https://cto.teamstation.dev/hire/by-technology/node",
  "https://cto.teamstation.dev/hire/by-technology/notion",
  "https://cto.teamstation.dev/hire/by-technology/objective-c",
  "https://cto.teamstation.dev/hire/by-technology/oidc",
  "https://cto.teamstation.dev/hire/by-technology/okta",
  "https://cto.teamstation.dev/hire/by-technology/opa",
  "https://cto.teamstation.dev/hire/by-technology/openai",
  "https://cto.teamstation.dev/hire/by-technology/opentelemetry",
  "https://cto.teamstation.dev/hire/by-technology/owasp-zap",
  "https://cto.teamstation.dev/hire/by-technology/pact",
  "https://cto.teamstation.dev/hire/by-technology/pgvector",
  "https://cto.teamstation.dev/hire/by-technology/php",
  "https://cto.teamstation.dev/hire/by-technology/playwright",
  "https://cto.teamstation.dev/hire/by-technology/postgresql",
  "https://cto.teamstation.dev/hire/by-technology/prisma",
  "https://cto.teamstation.dev/hire/by-technology/proofpoint",
  "https://cto.teamstation.dev/hire/by-technology/prometheus",
  "https://cto.teamstation.dev/hire/by-technology/pytest",
  "https://cto.teamstation.dev/hire/by-technology/python",
  "https://cto.teamstation.dev/hire/by-technology/pytorch",
  "https://cto.teamstation.dev/hire/by-technology/ragas",
  "https://cto.teamstation.dev/hire/by-technology/ray",
  "https://cto.teamstation.dev/hire/by-technology/react",
  "https://cto.teamstation.dev/hire/by-technology/react-native",
  "https/cto.teamstation.dev/hire/by-technology/redis",
  "https://cto.teamstation.dev/hire/by-technology/redux",
  "https://cto.teamstation.dev/hire/by-technology/ruby",
  "https://cto.teamstation.dev/hire/by-technology/salesforce",
  "https://cto.teamstation.dev/hire/by-technology/scikit-learn",
  "https://cto.teamstation.dev/hire/by-technology/sentry",
  "https://cto.teamstation.dev/hire/by-technology/snowflake",
  "https://cto.teamstation.dev/hire/by-technology/soc",
  "https://cto.teamstation.dev/hire/by-technology/socketio",
  "https://cto.teamstation.dev/hire/by-technology/sops",
  "https://cto.teamstation.dev/hire/by-technology/spark",
  "https://cto.teamstation.dev/hire/by-technology/sql",
  "https://cto.teamstation.dev/hire/by-technology/sqlalchemy",
  "https://cto.teamstation.dev/hire/by-technology/stripe",
  "https://cto.teamstation.dev/hire/by-technology/swift",
  "https://cto.teamstation.dev/hire/by-technology/tailwind",
  "https://cto.teamstation.dev/hire/by-technology/tanstack",
  "https://cto.teamstation.dev/hire/by-technology/terraform",
  "https://cto.teamstation.dev/hire/by-technology/testing",
  "https://cto.teamstation.dev/hire/by-technology/transformers",
  "https://cto.teamstation.dev/hire/by-technology/trivy",
  "https://cto.teamstation.dev/hire/by-technology/typeorm",
  "https://cto.teamstation.dev/hire/by-technology/typescript",
  "https://cto.teamstation.dev/hire/by-technology/vault",
  "https://cto.teamstation.dev/hire/by-technology/vite",
  "https://cto.teamstation.dev/hire/by-technology/vllm",
  "https://cto.teamstation.dev/hire/by-technology/vue",
  "https://cto.teamstation.dev/hire/by-technology/zuora",
  "https://cto.teamstation.dev/platform",
  "https://cto.teamstation.dev/playbook/bias-free-technical-hiring-axiom-cortex",
  "https://cto.teamstation.dev/playbook/build-vs-buy",
  "https://cto.teamstation.dev/playbook/hub",
  "https://cto.teamstation.dev.com/playbook/latam-economics",
  "https://cto.teamstation.dev/playbook/nearshore-vs-offshore",
  "https://cto.teamstation.dev/playbook/tco-model",
  "https://cto.teamstation.dev/pricing",
  "https://cto.teamstation.dev/process",
  "https://cto.teamstation.dev/research/axiom-cortex-scientific-report",
  "https://cto.teamstation.dev/research/hub",
  "https://cto.teamstation.dev/research/performance-evaluation-framework",
  "https://cto.teamstation.dev/research/performance-evaluation-report-example",
  "https://cto.teamstation.dev/research/technical-talent-evaluation-system",
  "https://cto.teamstation.dev/services/integrated-services",
  "https://cto.teamstation.dev/services/talent-onboarding",
  "https://cto.teamstation.dev/sitemap",
  "https://cto.teamstation.dev/technical-interview-evaluation",
  "https://cto.teamstation.dev/trust",
  "https://cto.teamstation.dev/privacy-policy",
  "https://cto.teamstation.dev/terms-of-service",
  "https://cto.teamstation.dev/comparisons/faq",
];

(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  const erroneousPages = [];

  for (const url of urls) {
    const consoleMessages = [];
    page.on('console', msg => {
      consoleMessages.push(msg.text());
    });

    try {
      // Correctly format the local URL
      const localUrl = url.replace("https://cto.teamstation.dev", "http://localhost:3000");
      await page.goto(localUrl, { waitUntil: 'networkidle0' });
      
      const hasHydrationError = consoleMessages.some(msg => 
        msg.includes('Warning: Did not expect server HTML to contain a') || 
        msg.includes('Error: Hydration failed because the initial UI does not match what was rendered on the server')
      );

      if (hasHydrationError) {
        erroneousPages.push(url);
        console.log(`❌ Hydration error found on: ${url}`);
      } else {
        console.log(`✅ No hydration errors on: ${url}`);
      }
    } catch (error) {
      console.error(`Failed to load ${url}:`, error);
    }

    consoleMessages.length = 0; // Clear for next page
  }

  if (erroneousPages.length > 0) {
    console.log('\nHydration errors were found on the following pages:');
    erroneousPages.forEach(url => console.log(url));
  } else {
    console.log('\nNo hydration errors were found on any of the pages.');
  }

  await browser.close();
})();
