// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Next.js Experts | TeamStation AI',
    description: 'Hire elite Next.js experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireNextjsPage() {
    return (
        <ProgrammaticContent
            technology="Next.js"
            description="Our Next.js experts are masters of the modern web. We vet for a deep understanding of Next.js's core principles, from its powerful rendering strategies to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
