
export const countries = [
    { name: 'Mexico', slug: 'mexico', pain: 'Need US time-zone overlap with a massive talent pool?', solution: 'Leverage the largest and most mature nearshore market, with deep expertise in enterprise software and a huge pool of bilingual engineers.', kpi: '3-hour overlap with PST/CST/EST' },
    { name: 'Colombia', slug: 'colombia', pain: 'Looking for a rapidly growing hub with strong bilingual skills?', solution: 'Tap into the vibrant ecosystems of Bogotá and Medellín, known for their adaptable workforce and strong government support for tech.', kpi: 'Top 5 in LATAM English proficiency' },
    { name: 'Brazil', slug: 'brazil', pain: 'Need talent for complex, large-scale systems?', solution: 'Access the largest talent pool in LATAM, with world-class expertise in FinTech, Data Science, and complex backend systems.', kpi: 'LATAM\'s #1 talent market by volume' },
    { name: 'Argentina', slug: 'argentina', pain: 'Searching for highly-educated, senior talent?', solution: 'Benefit from a mature market with exceptionally high English proficiency and a deep pool of senior and lead-level engineers.', kpi: 'Highest English proficiency in LATAM' },
    { name: 'Chile', slug: 'chile', pain: 'Require enterprise-grade stability and skills?', solution: 'Engage with one of the most stable and economically advanced countries in the region, with a strong emphasis on engineering and data science.', kpi: 'Regional leader in B2B/financial tech' },
    { name: 'Peru', slug: 'peru', pain: 'Need a cost-effective location without quality loss?', solution: 'Tap into a rising tech scene with a growing pool of skilled mobile and web developers known for their strong work ethic.', kpi: 'Strong cost/quality ratio' },
    { name: 'Costa Rica', slug: 'costa-rica', pain: 'Need a proven U.S. tech hub?', solution: 'Hire from a major hub for U.S. tech companies, with a highly educated, bilingual workforce accustomed to enterprise-level expectations.', kpi: 'Major hub for US tech companies' },
    { name: 'Uruguay', slug: 'uruguay', pain: 'Need a stable, digitally advanced tech hub?', solution: 'Access a highly skilled, specialized talent pool in one of LATAM\'s most digitally advanced countries, with excellent infrastructure.', kpi: 'Top software exporter per capita' },
    { name: 'Ecuador', slug: 'ecuador', pain: 'Seeking emerging talent with high potential?', solution: 'Explore an emerging talent market with a growing number of skilled engineers and a strong desire to work with U.S. companies.', kpi: 'Significant cost advantage' },
    { name: 'Guatemala', slug: 'guatemala', pain: 'Seeking a growing Central American tech hub?', solution: 'Leverage a growing pool of young, motivated engineers in a market with strong U.S. cultural ties and a focus on service industries.', kpi: 'Central Time Zone alignment' },
];
