// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Go Developers | TeamStation AI',
    description: 'Hire elite Go developers, vetted for their expertise in building high-performance, concurrent systems. Build your team with TeamStation AI.',
};

export default function HireGoPage() {
    return (
        <ProgrammaticContent
            technology="Go"
            description="Our Go developers are experts in building high-performance, concurrent systems. We vet for a deep understanding of Go\'s core principles, goroutines, channels, and performance optimization techniques. Our focus is on developers who can build expert, scalable, and maintainable backend systems."
            country={null}
        />
    );
}
