// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire MobX Experts | TeamStation AI',
    description: 'Hire elite MobX experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireMobXPage() {
    return (
        <ProgrammaticContent
            technology="MobX"
            description="Our MobX experts are masters of state management. We vet for a deep understanding of MobX's core principles, from its powerful observable state to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
