// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Elasticsearch Experts | TeamStation AI',
    description: 'Hire elite Elasticsearch experts, vetted for their expertise in building high-performance, scalable, and secure search and analytics solutions. Build your team with TeamStation AI.',
};

export default function HireElasticsearchPage() {
    return (
        <ProgrammaticContent
            technology="Elasticsearch"
            description="Our Elasticsearch experts are masters of search and analytics. We vet for a deep understanding of Elasticsearch's core principles, from its powerful query DSL to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable search and analytics solutions."
            country={null}
        />
    );
}
