// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire gRPC Experts | TeamStation AI',
    description: 'Hire elite gRPC experts, vetted for their expertise in building high-performance, scalable, and secure APIs. Build your team with TeamStation AI.',
};

export default function HireGRPCPage() {
    return (
        <ProgrammaticContent
            technology="gRPC"
            description="Our gRPC experts are masters of the modern API. We vet for a deep understanding of gRPC's core principles, from its powerful protocol buffers to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable APIs."
            country={null}
        />
    );
}
