// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Flow Experts | TeamStation AI',
    description: 'Hire elite Flow experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireFlowPage() {
    return (
        <ProgrammaticContent
            technology="Flow"
            description="Our Flow experts are masters of the modern web. We vet for a deep understanding of Flow's core principles, from its powerful type checking capabilities to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
