// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Domain Driven Design Experts | TeamStation AI',
    description: 'Hire elite Domain Driven Design experts, vetted for their expertise in building high-performance, scalable, and secure software systems. Build your team with TeamStation AI.',
};

export default function HireDomainDrivenDesignPage() {
    return (
        <ProgrammaticContent
            technology="Domain Driven Design"
            description="Our Domain Driven Design experts are masters of software design. We vet for a deep understanding of Domain Driven Design's core principles, from its powerful strategic design patterns to its robust tactical design patterns. Our focus is on engineers who can build expert, cost-effective, and maintainable software systems."
            country={null}
        />
    );
}
