// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Google Cloud Experts | TeamStation AI',
    description: 'Hire elite Google Cloud experts, vetted for their expertise in building high-performance, scalable, and secure cloud infrastructure. Build your team with TeamStation AI.',
};

export default function HireGoogleCloudPage() {
    return (
        <ProgrammaticContent
            technology="Google Cloud"
            description="Our Google Cloud experts are masters of the Google Cloud Platform. We vet for a deep understanding of Google Cloud's core principles, from its powerful compute and storage services to its robust security and networking capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable cloud infrastructure."
            country={null}
        />
    );
}
