// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire React Developers | TeamStation AI',
    description: 'Hire elite React developers, vetted for their expertise in scaling, performance optimization, and building expert component architectures. Build your team with TeamStation AI.',
};

export default function HireReactPage() {
    return (
        <ProgrammaticContent
            technology="React"
            description="Our React developers are experts in building scalable, high-performance user interfaces. We vet for a deep understanding of React\'s core principles, state management solutions (like Redux or Zustand), and performance optimization techniques. Our focus is on developers who can build expert component architectures that are both maintainable and extensible."
            country={null}
        />
    );
}
