// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Feast Experts | TeamStation AI',
    description: 'Hire elite Feast experts, vetted for their expertise in building high-performance, scalable, and secure feature stores. Build your team with TeamStation AI.',
};

export default function HireFeastPage() {
    return (
        <ProgrammaticContent
            technology="Feast"
            description="Our Feast experts are masters of the feature store. We vet for a deep understanding of Feast's core principles, from its powerful feature definition and serving capabilities to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable feature stores."
            country={null}
        />
    );
}
