// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire DVC Experts | TeamStation AI',
    description: 'Hire elite DVC experts, vetted for their expertise in building high-performance, scalable, and secure data versioning systems. Build your team with TeamStation AI.',
};

export default function HireDVCPage() {
    return (
        <ProgrammaticContent
            technology="DVC"
            description="Our DVC experts are masters of data versioning. We vet for a deep understanding of DVC's core principles, from its powerful data versioning and experiment tracking features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable data versioning systems."
            country={null}
        />
    );
}
