// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Microservices Experts | TeamStation AI',
    description: 'Hire elite Microservices experts, vetted for their expertise in building high-performance, scalable, and secure distributed systems. Build your team with TeamStation AI.',
};

export default function HireMicroservicesPage() {
    return (
        <ProgrammaticContent
            technology="Microservices"
            description="Our Microservices experts are masters of distributed systems. We vet for a deep understanding of Microservices' core principles, from its powerful service decomposition and communication patterns to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable distributed systems."
            country={null}
        />
    );
}
