// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Data Engineering Developers | TeamStation AI',
    description: 'Hire elite Data Engineering developers, vetted for their expertise in building high-performance, scalable, and secure data infrastructure. Build your team with TeamStation AI.',
};

export default function HireDataEngineeringPage() {
    return (
        <ProgrammaticContent
            technology="Data Engineering"
            description="Our Data Engineering developers are experts in building high-performance, scalable, and secure data infrastructure. We vet for a deep understanding of Data Engineering's core principles, ETL/ELT pipelines, and cloud data platforms. Our focus is on developers who can build expert, cost-effective, and maintainable data-native systems."
            country={null}
        />
    );
}
