// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Android Experts | TeamStation AI',
    description: 'Hire elite Android experts, vetted for their expertise in building high-performance, scalable, and secure Android applications. Build your team with TeamStation AI.',
};

export default function HireAndroidPage() {
    return (
        <ProgrammaticContent
            technology="Android"
            description="Our Android experts are masters of the Android platform. We vet for a deep understanding of Android's core principles, from its activity lifecycle to its security features. Our focus is on engineers who can build expert, cost-effective, and maintainable Android applications."
            country={null}
        />
    );
}
