// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Nuxt.js Experts | TeamStation AI',
    description: 'Hire elite Nuxt.js experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireNuxtjsPage() {
    return (
        <ProgrammaticContent
            technology="Nuxt.js"
            description="Our Nuxt.js experts are masters of the Vue.js framework. We vet for a deep understanding of Nuxt.js's core principles, from its powerful server-side rendering to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
