// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire AWS Developers | TeamStation AI',
    description: 'Hire elite AWS developers, vetted for their expertise in building high-performance, scalable, and secure cloud infrastructure. Build your team with TeamStation AI.',
};

export default function HireAWSPage() {
    return (
        <ProgrammaticContent
            technology="AWS"
            description="Our AWS developers are experts in building high-performance, scalable, and secure cloud infrastructure. We vet for a deep understanding of AWS's core services, infrastructure as code, and FinOps principles. Our focus is on developers who can build expert, cost-effective, and maintainable cloud-native systems."
            country={null}
        />
    );
}
