// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Docker Experts | TeamStation AI',
    description: 'Hire elite Docker experts, vetted for their expertise in building high-performance, scalable, and secure containerized applications. Build your team with TeamStation AI.',
};

export default function HireDockerPage() {
    return (
        <ProgrammaticContent
            technology="Docker"
            description="Our Docker experts are masters of containerization. We vet for a deep understanding of Docker's core principles, from its powerful container runtime to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable containerized applications."
            country={null}
        />
    );
}
