// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire OWASP ZAP Experts | TeamStation AI',
    description: 'Hire elite OWASP ZAP experts, vetted for their expertise in building high-performance, scalable, and secure web application security tests. Build your team with TeamStation AI.',
};

export default function HireOwaspZapPage() {
    return (
        <ProgrammaticContent
            technology="OWASP ZAP"
            description="Our OWASP ZAP experts are masters of web application security testing. We vet for a deep understanding of OWASP ZAP's core principles, from its powerful automated scanning to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable web application security tests."
            country={null}
        />
    );
}
