// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire GraphQL Experts | TeamStation AI',
    description: 'Hire elite GraphQL experts, vetted for their expertise in building high-performance, scalable, and secure APIs. Build your team with TeamStation AI.',
};

export default function HireGraphQLPage() {
    return (
        <ProgrammaticContent
            technology="GraphQL"
            description="Our GraphQL experts are masters of the modern API. We vet for a deep understanding of GraphQL's core principles, from its powerful query language to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable APIs."
            country={null}
        />
    );
}
