// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Grafana Experts | TeamStation AI',
    description: 'Hire elite Grafana experts, vetted for their expertise in building high-performance, scalable, and secure observability solutions. Build your team with TeamStation AI.',
};

export default function HireGrafanaPage() {
    return (
        <ProgrammaticContent
            technology="Grafana"
            description="Our Grafana experts are masters of observability. We vet for a deep understanding of Grafana's core principles, from its powerful data visualization and dashboarding features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable observability solutions."
            country={null}
        />
    );
}
