// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Java Developers | TeamStation AI',
    description: 'Hire elite Java developers, vetted for their expertise in enterprise-grade, cloud-native applications using Spring Boot and modern Java features. Build your team with TeamStation AI.',
};

export default function HireJavaPage() {
    return (
        <ProgrammaticContent
            technology="Java"
            description="Our Java developers are experts in building robust, enterprise-grade, cloud-native applications. Our vetting process focuses on a deep understanding of the Spring Boot ecosystem, microservices architecture, and modern Java features. We test for proficiency in building scalable, resilient systems ready for the cloud."
            country={null}
        />
    );
}
