// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Django Experts | TeamStation AI',
    description: 'Hire elite Django experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireDjangoPage() {
    return (
        <ProgrammaticContent
            technology="Django"
            description="Our Django experts are masters of the Python framework. We vet for a deep understanding of Django's core principles, from its powerful ORM to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
