// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire API Security Experts | TeamStation AI',
    description: 'Hire elite API Security experts, vetted for their expertise in building high-performance, scalable, and secure APIs. Build your team with TeamStation AI.',
};

export default function HireAPISecurityPage() {
    return (
        <ProgrammaticContent
            technology="API Security"
            description="Our API Security experts are masters of API protection. We vet for a deep understanding of API Security's core principles, from its powerful authentication and authorization features to its robust encryption and throttling capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable APIs."
            country={null}
        />
    );
}
