// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Kubernetes Experts | TeamStation AI',
    description: 'Hire elite Kubernetes experts, vetted for their expertise in building high-performance, scalable, and secure containerized infrastructure. Build your team with TeamStation AI.',
};

export default function HireKubernetesPage() {
    return (
        <ProgrammaticContent
            technology="Kubernetes"
            description="Our Kubernetes experts are masters of container orchestration. We vet for a deep understanding of Kubernetes architecture, from the control plane to the worker nodes, and the ability to design and manage complex, mission-critical deployments. Our focus is on engineers who can build expert, cost-effective, and maintainable cloud-native systems."
            country={null}
        />
    );
}
