// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire API Gateway Experts | TeamStation AI',
    description: 'Hire elite API Gateway experts, vetted for their expertise in building high-performance, scalable, and secure API gateways. Build your team with TeamStation AI.',
};

export default function HireAPIGatewayPage() {
    return (
        <ProgrammaticContent
            technology="API Gateway"
            description="Our API Gateway experts are masters of API management. We vet for a deep understanding of API Gateway's core principles, from its powerful routing and caching features to its robust security and throttling capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable API gateways."
            country={null}
        />
    );
}
