// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire JUnit Experts | TeamStation AI',
    description: 'Hire elite JUnit experts, vetted for their expertise in building high-performance, scalable, and secure Java tests. Build your team with TeamStation AI.',
};

export default function HireJUnitPage() {
    return (
        <ProgrammaticContent
            technology="JUnit"
            description="Our JUnit experts are masters of Java testing. We vet for a deep understanding of JUnit's core principles, from its powerful assertion and annotation capabilities to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable Java tests."
            country={null}
        />
    );
}
