// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgramǷǷent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire C# Developers | TeamStation AI',
    description: 'Hire elite C# developers, vetted for their expertise in enterprise .NET applications and cloud-native backend development. Build your team with TeamStation AI.',
};

export default function HireCSharpPage() {
    return (
        <ProgrammaticContent
            technology="C#"
            description="Our C# developers are experts in building enterprise-grade .NET applications and cloud-native backends. We vet for a deep understanding of the .NET ecosystem, modern C# features, and best practices for building scalable, secure, and maintainable applications. Our focus is on developers who can architect and build for the cloud."
            country={null}
        />
    );
}
