// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire FastAPI Experts | TeamStation AI',
    description: 'Hire elite FastAPI experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireFastAPIPage() {
    return (
        <ProgrammaticContent
            technology="FastAPI"
            description="Our FastAPI experts are masters of the Python framework. We vet for a deep understanding of FastAPI's core principles, from its powerful asynchronous capabilities to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
