// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Jenkins Experts | TeamStation AI',
    description: 'Hire elite Jenkins experts, vetted for their expertise in building high-performance, scalable, and secure software delivery pipelines. Build your team with TeamStation AI.',
};

export default function HireJenkinsPage() {
    return (
        <ProgrammaticContent
            technology="Jenkins"
            description="Our Jenkins experts are masters of automation. We vet for a deep understanding of Jenkins's core principles, from its powerful pipeline-as-code features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable software delivery pipelines."
            country={null}
        />
    );
}
