// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Kubeflow Experts | TeamStation AI',
    description: 'Hire elite Kubeflow experts, vetted for their expertise in building high-performance, scalable, and secure machine learning pipelines. Build your team with TeamStation AI.',
};

export default function HireKubeflowPage() {
    return (
        <ProgrammaticContent
            technology="Kubeflow"
            description="Our Kubeflow experts are masters of machine learning pipelines. We vet for a deep understanding of Kubeflow's core principles, from its powerful pipeline authoring and execution features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable machine learning pipelines."
            country={null}
        />
    );
}
