// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Locust Experts | TeamStation AI',
    description: 'Hire elite Locust experts, vetted for their expertise in building high-performance, scalable, and secure load testing solutions. Build your team with TeamStation AI.',
};

export default function HireLocustPage() {
    return (
        <ProgrammaticContent
            technology="Locust"
            description="Our Locust experts are masters of load testing. We vet for a deep understanding of Locust's core principles, from its powerful Python-based scripting to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable load testing solutions."
            country={null}
        />
    );
}
