// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Node.js Developers | TeamStation AI',
    description: 'Hire elite Node.js developers, vetted for their expertise in building high-performance, concurrent systems. Build your team with TeamStation AI.',
};

export default function HireNodePage() {
    return (
        <ProgrammaticContent
            technology="Node.js"
            description="Our Node.js developers are experts in building high-performance, concurrent systems. We vet for a deep understanding of Node.js\'s core principles, event loop, and performance optimization techniques. Our focus is on developers who can build expert, scalable, and maintainable backend systems."
            country={null}
        />
    );
}
