// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Node.js Developers | TeamStation AI',
    description: 'Hire elite Node.js developers, vetted for their expertise in building scalable microservices and high-throughput, non-blocking APIs. Build your team with TeamStation AI.',
};

export default function HireNodePage() {
    return (
        <ProgrammaticContent
            technology="Node.js"
            description="Our Node.js developers are experts in building and scaling high-throughput, non-blocking APIs. We focus on a deep understanding of the event loop, libuv, and modern async/await patterns. Our vetting emphasizes experience with structured frameworks like NestJS or Fastify, API security best practices, and performance tuning."
            country={null}
        />
    );
}
