// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Jakarta EE Experts | TeamStation AI',
    description: 'Hire elite Jakarta EE experts, vetted for their expertise in building high-performance, scalable, and secure enterprise applications. Build your team with TeamStation AI.',
};

export default function HireJakartaEEPage() {
    return (
        <ProgrammaticContent
            technology="Jakarta EE"
            description="Our Jakarta EE experts are masters of the enterprise Java framework. We vet for a deep understanding of Jakarta EE's core principles, from its powerful component model to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable enterprise applications."
            country={null}
        />
    );
}
