// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Jest Experts | TeamStation AI',
    description: 'Hire elite Jest experts, vetted for their expertise in building high-performance, scalable, and secure JavaScript tests. Build your team with TeamStation AI.',
};

export default function HireJestPage() {
    return (
        <ProgrammaticContent
            technology="Jest"
            description="Our Jest experts are masters of JavaScript testing. We vet for a deep understanding of Jest's core principles, from its powerful mocking and assertion capabilities to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable JavaScript tests."
            country={null}
        />
    );
}
