// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire DevOps Engineers | TeamStation AI',
    description: 'Hire elite DevOps engineers, vetted for their expertise in SRE principles, cloud architecture (AWS/GCP/Azure), and CI/CD automation. Build your team with TeamStation AI.',
};

export default function HireDevOpsPage() {
    return (
        <ProgrammaticContent
            technology="DevOps"
            description="Our DevOps engineers are experts in SRE principles, cloud architecture, and CI/CD automation. We vet for a deep understanding of infrastructure-as-code (Terraform, Pulumi), containerization (Docker, Kubernetes), and observability (Prometheus, Grafana). Our focus is on engineers who can build and maintain scalable, resilient, and secure infrastructure."
            country={null}
        />
    );
}
