// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire DevOps Engineers | TeamStation AI',
    description: 'Hire elite DevOps Engineers, vetted for their expertise in building high-performance, scalable, and secure cloud infrastructure. Build your team with TeamStation AI.',
};

export default function HireDevOpsEngineeringPage() {
    return (
        <ProgrammaticContent
            technology="DevOps Engineering"
            description="Our DevOps Engineers are experts in building high-performance, scalable, and secure cloud infrastructure. We vet for a deep understanding of DevOps principles, CI/CD pipelines, and cloud-native technologies. Our focus is on developers who can build expert, cost-effective, and maintainable systems."
            country={null}
        />
    );
}
