// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Generative AI Experts | TeamStation AI',
    description: 'Hire elite Generative AI experts, vetted for their expertise in building high-performance, scalable, and secure AI-powered applications. Build your team with TeamStation AI.',
};

export default function HireGenerativeAIPage() {
    return (
        <ProgrammaticContent
            technology="Generative AI"
            description="Our Generative AI experts are masters of creating novel content. We vet for a deep understanding of Generative AI architecture, from GANs to VAEs, and the latest techniques in text-to-image and text-to-video generation. Our focus is on engineers who can build expert, cost-effective, and maintainable AI-powered applications."
            country={null}
        />
    );
}
