// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Cypress Experts | TeamStation AI',
    description: 'Hire elite Cypress experts, vetted for their expertise in building high-performance, scalable, and secure end-to-end tests. Build your team with TeamStation AI.',
};

export default function HireCypressPage() {
    return (
        <ProgrammaticContent
            technology="Cypress"
            description="Our Cypress experts are masters of end-to-end testing. We vet for a deep understanding of Cypress's core principles, from its powerful command-line interface to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable end-to-end tests."
            country={null}
        />
    );
}
