// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire CodeIgniter Experts | TeamStation AI',
    description: 'Hire elite CodeIgniter experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireCodeIgniterPage() {
    return (
        <ProgrammaticContent
            technology="CodeIgniter"
            description="Our CodeIgniter experts are masters of the PHP framework. We vet for a deep understanding of CodeIgniter's core principles, from its powerful MVC architecture to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
