// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Snowflake Experts | TeamStation AI',
    description: 'Hire elite Snowflake experts, vetted for their expertise in building high-performance, scalable, and secure data warehousing solutions. Build your team with TeamStation AI.',
};

export default function HireSnowflakePage() {
    return (
        <ProgrammaticContent
            technology="Snowflake"
            description="Our Snowflake experts are masters of the data cloud. We vet for a deep understanding of Snowflake's unique architecture, from its multi-cluster, shared data architecture to its powerful features like Snowpipe and Time Travel. Our focus is on engineers who can build expert, cost-effective, and maintainable data warehousing solutions."
            country={null}
        />
    );
}
