// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Micronaut Experts | TeamStation AI',
    description: 'Hire elite Micronaut experts, vetted for their expertise in building high-performance, scalable, and secure microservices. Build your team with TeamStation AI.',
};

export default function HireMicronautPage() {
    return (
        <ProgrammaticContent
            technology="Micronaut"
            description="Our Micronaut experts are masters of the modern microservice. We vet for a deep understanding of Micronaut's core principles, from its powerful dependency injection and AOP features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable microservices."
            country={null}
        />
    );
}
