// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Cloudformation Experts | TeamStation AI',
    description: 'Hire elite Cloudformation experts, vetted for their expertise in building high-performance, scalable, and secure cloud infrastructure. Build your team with TeamStation AI.',
};

export default function HireCloudformationPage() {
    return (
        <ProgrammaticContent
            technology="Cloudformation"
            description="Our Cloudformation experts are masters of Infrastructure as Code. We vet for a deep understanding of Cloudformation's core principles, from writing clean and modular templates to managing complex, multi-cloud deployments. Our focus is on engineers who can build expert, cost-effective, and maintainable cloud-native systems."
            country={null}
        />
    );
}
