// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Cassandra Experts | TeamStation AI',
    description: 'Hire elite Cassandra experts, vetted for their expertise in building high-performance, scalable, and secure distributed databases. Build your team with TeamStation AI.',
};

export default function HireCassandraPage() {
    return (
        <ProgrammaticContent
            technology="Cassandra"
            description="Our Cassandra experts are masters of the distributed database. We vet for a deep understanding of Cassandra's core principles, from its powerful data modeling and partitioning features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable distributed databases."
            country={null}
        />
    );
}
