// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire MySQL Experts | TeamStation AI',
    description: 'Hire elite MySQL experts, vetted for their expertise in building high-performance, scalable, and secure relational databases. Build your team with TeamStation AI.',
};

export default function HireMySQLPage() {
    return (
        <ProgrammaticContent
            technology="MySQL"
            description="Our MySQL experts are masters of the relational database. We vet for a deep understanding of MySQL's core principles, from its powerful data modeling and indexing features to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable relational databases."
            country={null}
        />
    );
}
