// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire AIX Experts | TeamStation AI',
    description: 'Hire elite AIX experts, vetted for their expertise in managing and maintaining IBM AIX systems. Build your team with TeamStation AI.',
};

export default function HireAIXPage() {
    return (
        <ProgrammaticContent
            technology="AIX"
            description="Our AIX experts are masters of the IBM AIX operating system. We vet for a deep understanding of AIX's core principles, from its logical volume manager to its security features. Our focus is on engineers who can build expert, cost-effective, and maintainable AIX systems."
            country={null}
        />
    );
}
