// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Python Developers | TeamStation AI',
    description: 'Hire elite Python developers, vetted for their expertise in both backend web development (Django/Flask) and Data/AI pipelines. Build your team with TeamStation AI.',
};

export default function HirePythonPage() {
    return (
        <ProgrammaticContent
            technology="Python"
            description="Our Python developers are versatile experts, vetted for their proficiency in both backend web development with frameworks like Django and Flask, and their ability to build robust data and AI pipelines. We test for a deep understanding of Python\'s concurrency models, data structures, and the scientific computing stack (NumPy, Pandas, etc.)."
            country={null}
        />
    );
}
