// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Terraform Experts | TeamStation AI',
    description: 'Hire elite Terraform experts, vetted for their expertise in building high-performance, scalable, and secure cloud infrastructure. Build your team with TeamStation AI.',
};

export default function HireTerraformPage() {
    return (
        <ProgrammaticContent
            technology="Terraform"
            description="Our Terraform experts are masters of Infrastructure as Code. We vet for a deep understanding of Terraform's core principles, from writing clean and modular code to managing complex, multi-cloud deployments. Our focus is on engineers who can build expert, cost-effective, and maintainable cloud-native systems."
            country={null}
        />
    );
}
