// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire .NET Experts | TeamStation AI',
    description: 'Hire elite .NET experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireDotNetPage() {
    return (
        <ProgrammaticContent
            technology=".NET"
            description="Our .NET experts are masters of the Microsoft ecosystem. We vet for a deep understanding of .NET's core principles, from its powerful runtime to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
