// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Axiom Cortex Experts | TeamStation AI',
    description: 'Hire elite Axiom Cortex experts, vetted for their expertise in building high-performance, scalable, and secure AI-powered applications. Build your team with TeamStation AI.',
};

export default function HireAxiomCortexPage() {
    return (
        <ProgrammaticContent
            technology="Axiom Cortex"
            description="Our Axiom Cortex experts are masters of our proprietary AI-powered vetting platform. We vet for a deep understanding of Axiom Cortex's core principles, from its powerful cognitive assessments to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable AI-powered applications."
            country={null}
        />
    );
}
