// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Algol Experts | TeamStation AI',
    description: 'Hire elite Algol experts, vetted for their expertise in managing and maintaining legacy Algol systems. Build your team with TeamStation AI.',
};

export default function HireAlgolPage() {
    return (
        <ProgrammaticContent
            technology="Algol"
            description="Our Algol experts are masters of the Algol programming language. We vet for a deep understanding of Algol's core principles and its historical significance. Our focus is on engineers who can maintain and modernize legacy systems written in Algol."
            country={null}
        />
    );
}
