// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire Helm Experts | TeamStation AI',
    description: 'Hire elite Helm experts, vetted for their expertise in building high-performance, scalable, and secure Kubernetes applications. Build your team with TeamStation AI.',
};

export default function HireHelmPage() {
    return (
        <ProgrammaticContent
            technology="Helm"
            description="Our Helm experts are masters of Kubernetes package management. We vet for a deep understanding of Helm's core principles, from its powerful templating engine to its robust security and performance tuning capabilities. Our focus is on engineers who can build expert, cost-effective, and maintainable Kubernetes applications."
            country={null}
        />
    );
}
