// This file is autogenerated by the Sentinel AI.
// Any changes made to this file will be overwritten.
import { ProgrammaticContent } from '@/components/ProgrammaticContent';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Hire jQuery Experts | TeamStation AI',
    description: 'Hire elite jQuery experts, vetted for their expertise in building high-performance, scalable, and secure web applications. Build your team with TeamStation AI.',
};

export default function HireJqueryPage() {
    return (
        <ProgrammaticContent
            technology="jQuery"
            description="Our jQuery experts are masters of the classic JavaScript library. We vet for a deep understanding of jQuery's core principles, from its powerful DOM manipulation to its growing ecosystem of integrations. Our focus is on engineers who can build expert, cost-effective, and maintainable web applications."
            country={null}
        />
    );
}
